### ISSUE TITLE
Wrong ZITADEL Logo on dark theme

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#2085]
As an enduser I want to see the logo of my organization defined on my current theme (datk/light)

**Acceptance *Criteria**
- [ ] When I have dark theme as default I see the logo of the dark theme also on the first time I open ZITADEL
- [ ] When I have light theme as default I see the logo of the light theme also on the first time I open ZITADEL

**Describe the bug**
When I click on 'Register' on zitadel.ch - in dark theme - the ZITADEL logo is the light theme one, instead of the dark theme one. (white font etc..) And as such hard to see/read.

![image](https://user-images.githubusercontent.com/48990649/127280818-c408c3ea-e766-467b-9655-b16d03d31a2a.png)

Windows 10, Firefox 90.0.2

**Comment by adlerhurst** [comment]
after a reload i got the white zitadel logo.

**Comment by livio-a** [comment]
a reload will fix it only temporary... after switching between dark/light mode the bug will reoccur
seems like a timing issue in the rendering process

**Comment by peintnermax** [comment]
@livio-a we should specify .zitadel.ch as the domain for the mode cookie such that console can set its theme across all our domains

**Comment by livio-a** [comment]
@peintnermax this would certainly improve the overall theming experience

problem here is that we render the page including the logo from the backend (dark or light) and then have a media query and javascript which might change the from light to dark or reverse
cookie and all css will be applied correctly but the logo stays the same (src is from backend)

**Comment by mffap** [comment]
@hifabienne is this still relevant?

**Comment by hifabienne** [comment]
> @hifabienne is this still relevant?

yes

**Comment by vs-gtadeu** [comment]
I quickly looked at the code that handles the dark/light color mode logic. It seems the problem is that the backend relies on the cookie to select which image to use, but the cookie is only managed by the client using some browser-dependent logic, which requires users to visit the page at least once to see the correct logo.

Since the logic to select the correct color mode is browser-dependent and thus happens on the client side, my suggestion to solve this problem is to handle logo selection logic on the client side as well.
This could be done by having the backend include the HTML elements of the two images with one or more distinct CSS classes to identify which color mode each image is associated with. After that, some JavaScript code can be used to toggle the correct color mode by adding a CSS class to a top-level element (e.g., `<body>`) while some CSS rules can be implemented to hide/show the appropriate logo based on that top-level element CSS class.
