### ISSUE TITLE
Miss cache for changed resources

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#3833]
When console assets change, cache should be missed (e.g. zitadel.css)

For example, add an ETag header.
https://sidney.kochman.org/2018/etag-middleware-go/

Could it be generated at build time for console assets for better performance?

**Comment by livio-a** [comment]
When console assets (js files) change they get a new name, so there's no problem. The index file is served with a `Last-Modified` header which points to the time the goreleaser command built the go binary. Its `Cache-Control` header is set to 5min shared cache, no local cache.

All static assets of the login (zitadel.css, ...) are served with a `Last-Modified` header as well and a `Cache-Control` of 12 hours local and 7 days shared.
Dynamic assets (label policy overwrite of zitadel.css) is served with an ETag header computed and stored in the database.

So IMO the only issue we currently have is, if we change something in zitadel.css. It will take up to 12 hours to get the change to the client (because of local cache). Shared cache should not be a problem as it can revalidate using the `Last-Modified` header.
