### ISSUE TITLE
Design Service Users

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3953]
At the moment we have in the console the menu users. In this we can switch between users and service users. The part for service users is often hard to find, and some users took the api to create the service users, because they didn't know where to do it in the console.
Maybe we can change the ux to make it more clear to the users.

<img width="848" alt="image" src="https://user-images.githubusercontent.com/38692350/178667181-24c2ef56-7464-4605-bb0c-2f1004d1e92a.png">

**Acceptance criteria**
- [ ] Design for service users

**Comment by juergrinaldi** [comment]
As mentioned in the chat channel my input for this issue is as follows:

I'd still suggest to have a more consistent theme for (main) clickable links as applying the keycolor to all the clickable elements to make it more visible to the user.

Furthermore, we could make the switch for Users/Service Users in the same style as the 1st navigation (as it is in a way like a 2nd level navigation).

![image](https://user-images.githubusercontent.com/48990649/180730577-39291d16-4955-499d-9b6b-fe8e8a6f3e2d.png)

Some alternative approaches:
a) We could test a variant where we don't separate the two users and just add a filter/sort option for the two types of users. Keep in mind though, that this would probably lead to another column in the table (for 'type'). To differentiate it more we could use icons instead (human-like icon for normal users, robot or clogs for service users)

b) Max suggested to use the regular second level navigation (sidebar). this would be consistent with the general UI/UX but takes away even more real estate than a) and might be unnecessary. But it might be worth an A/B test.

Talking about A/B testing: I think it would be very insightful to do some A/B testing with these suggestions to see what is accepted best by the userbase.
