### ISSUE TITLE
Register Email: No Logo showing (in GMail)

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4058]
ZITADEL Logo isn't showing in the register email in GMail (Chrome):

![Image](https://user-images.githubusercontent.com/48990649/181207330-deafad25-0e5f-474c-bb37-b6954384e910.png)

**Comment by hifabienne** [comment]
@juergrinaldi what kind of settings do you have for instance? I just tried it myself with Chrome and I don't have this bug. Unfortunately I never get the logo even if I have configured it

**Comment by juergrinaldi** [comment]
Which settings do you mean?

BTW: It's only on the register mail, in the follow-up mail (start build your project with ZITADEL) the logo is showing. (so I doubt it has anything to do with my settings)

**Comment by hifabienne** [comment]
duplicate #4191

**Comment by livio-a** [comment]
i believe so... (https://github.com/zitadel/zitadel/pull/4426)

**Comment by TakumiHaruta** [comment]
@livio-a @hifabienne 

Hi there,

Logo is still not showing in Gmail when Zitadel is being self-hosted in AWS.
The cause seems to be because of Google Image Proxy.

- [html - Email thumbnail URL changed to googleusercontent.com in gmail - Stack Overflow](https://stackoverflow.com/questions/51471607/email-thumbnail-url-changed-to-googleusercontent-com-in-gmail)
- [Gmail's new image caching is breaking image links in newsletter - Stack Overflow](https://stackoverflow.com/questions/20903967/gmails-new-image-caching-is-breaking-image-links-in-newsletter)

When I read a notification email in Gmail, the `src` tag is like `https://ci3.googleusercontent.com/proxy/xxxxxx#https://example.com/assets/v1/202149668845539911/policy/label/logo-203987936088187679`, while actual HTML which can be downloaded is like `https://example.com/assets/v1/202149175947711047/policy/label/logo-203852510081868575` and I could see the logo when I open it as HTML.

According to StackOverflow, the image URL needs the extension of the image to let Google Image Proxy server fetch it, but the extention is missing in the `src` tag of HTML, which might be the cause I guess...?

Is it possible to add the extension to `https://example.com/assets/v1/202149175947711047/policy/label/logo-203852510081868575` for Gmail issue?
If it doesn't work, there could be other missing configurations but I'm not sure how Asset API is designed and which part doesn't meet the requirements as an image server for Google
