### ISSUE TITLE
Initialise Email

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4191]
The initialise mail should be improved, also the focus is more on the code instead of the button.

**Acceptance criteria**
- [x] Ensure logo is shown
- [ ] Use font from branding
- [ ] Focus should be on button (see pictures below)
- [ ] Text should not say user created in ZITADEL, should say user created in org xy

**Comment by hifabienne** [comment]
New: 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/38692350/184827779-d49cab73-1a15-4354-b6b4-c67dfa5bcf4a.png">

Old:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/38692350/184827807-44b5f3e2-bf36-482b-96cf-c1ba83c42d90.png">

**Comment by hifabienne** [comment]
@livio-a is the logo problem solved with your fix?

**Comment by livio-a** [comment]
> @livio-a is the logo problem solved with your fix?

i think this was one part of it... but https://github.com/zitadel/zitadel/pull/4149 also helped by disabling svg uploads

**Comment by peintnermax** [comment]
Loading fonts is an difficult topic for emails as those are often blocked by email clients,
and changing the template is currently not possible due to the fact that we are using one single template for all messages.
We should provide an API for users to upload their own html template for each email type

**Comment by hifabienne** [comment]
I will close this issue as we will get rid of the init mmail anyway
