### ISSUE TITLE
Not found message in language

### ISSUE THREAD

**Issue by jinrenjie** [zitadel/zitadel#4205]
**Describe the bug**
Not found message in language when send reset password email notification to user

**To Reproduce**
1. Go to login page
2. Click reset password button
3. Click next button
4. See logs in zitadel server

**Expected behavior**
Receive email notification of recharge password.

**Screenshots**
![WeCom20220817-120735](https://user-images.githubusercontent.com/5665135/185032684-b7d69c43-df4c-4f4f-b0c1-b45ac81f6c9b.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 104.0.5112.79

**Additional context**

**Comment by livio-a** [comment]
Hey @jinrenjie 

I see two problems in the logs:
- logging the whole message because of the missing footer translation <- is not bad but ugly
- "Errors.Notification.Channels.NotPresent" indicates that on your instance no notification channel is configured,
which means that you need to configure an smtp for example

The SMTP can be configured in the config (https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml#L373) before creating the instance or afterwards using the Console UI: https://docs.zitadel.com/docs/concepts/structure/policies#smtp
However, there is currently a problem with this, which will be solved shortly: https://github.com/zitadel/zitadel/issues/4215

**Comment by jinrenjie** [comment]
@livio-a Thanks for your reply. The SMTP config configuration was successful, but I found some unfriendly places for newbies. The input box of the SMTP host has no placeholder for prompting that the required format is domain:port, which led me to try many times and complete the configuration with the error log.

**Comment by livio-a** [comment]
@jinrenjie Great to hear, that at least now it works and thanks for the feedback. We'll adjust that in the UI and config yaml.

**Comment by fforootd** [comment]
Lets close this in favor of [#4215](https://github.com/zitadel/zitadel/issues/4215)
