### ISSUE TITLE
Client Credentials for service accounts

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#4211]
As a developer I want to be able to use client credentials as grant on a service user.

**Acceptance criteria**
- [x] I am able to generate a client credential on my service account
- [x] I am able to authenticate my service account with client credentials
- [x] Implemented according to: [Client Credentials Grant](https://www.rfc-editor.org/rfc/rfc6749#section-4.4)

**Additional Context**
Service accounts can authenticate using JWT Profile. As alternative you can directly generate a PAT for authorization.

While JWT Profile is very secure it's not always supported by 3rd party tools or too complicated for certain uses cases.
PATs are as well not always supported and not the best choice regarding security (in certain use cases you can ensure that they will be rotated, ...).

We should therefore provide a 3rd option where you can generate a password and use it for [Client Credentials Grant](https://www.rfc-editor.org/rfc/rfc6749#section-4.4)

**Comment by mffap** [comment]
Related discussion: 
https://github.com/zitadel/zitadel/discussions/2535

and also https://github.com/zitadel/zitadel/discussions/4009

**Comment by hifabienne** [comment]
@fforootd Not sure why you are assigned to this. I remove you. Feel free to reassigne if needed.

**Comment by Frank-D** [comment]
`+1` on adding support for `Oauth2 Client Credentials` grant type!
(a **widely** used and **simple** service-to-service | machine-to-machine authentication method in the industry)

(e.g. allowing authentication using client credentials [client/secret] for service accounts, so that a client app. can obtain an access token by calling zitadel [e.g. authorization server]'s /token endpoint, by providing those client/secret to that token endpoint (either in the form of a standard [basic auth] header param, or as extra url params e.g. /token?grant_type=client_credentials&client_id=abc&client_secret=xyz), of course by matching the client app's client/secret with a corresponding 'service account' defined in zitadel first. Then, once such access token returned by the zitadel's /token endpoint to the client app., that token can then be used by such client app as a bearer header auth. token to access protected resources of the 'resources server' app.)

Ref.: https://github.com/zitadel/zitadel/issues/500 
(not sure why this feature request was closed in the first placed, perhaps because it may have deviated from the original feature request description through the comments into a documentation clarification which got resolved, which ended up responsible for closing the issue, but in the end, the 'oauth2 client credentials grant type' feature is still missing, hence the feature request should remain open, but I guess current issue is now the official tracker for such feature, and it seems like so since I see from the above it was added to the Prioritized Product Backlog, so if that's the case, great news)

For the record, the lack of this feature would prevent me from migrating a multi-tenants use case from keycloak to zitadel, since just too many tenants rely on oauth2 client credentials method, to access non-interactive/service-to-service protected REST APIs.

I'll be watching this issue/FR, thanks!

**Comment by fforootd** [comment]
> +1 on adding support for Oauth2 Client Credentials grant type!
(a widely used and simple service-to-service | machine-to-machine authentication method in the industry)

(e.g. allowing authentication using client credentials [client/secret] for service accounts, so that a client app. can obtain an access token by calling zitadel [e.g. authorization server]'s /token endpoint, by providing those client/secret to that token endpoint (either in the form of a standard [basic auth] header param, or as extra url params e.g. /token?grant_type=client_credentials&client_id=abc&client_secret=xyz), of course by matching the client app's client/secret with a corresponding 'service account' defined in zitadel first. Then, once such access token returned by the zitadel's /token endpoint to the client app., that token can then be used by such client app as a bearer header auth. token to access protected resources of the 'resources server' app.)

Ref.: https://github.com/zitadel/zitadel/issues/500
(not sure why this feature request was closed in the first placed, perhaps because it may have deviated from the original feature request description through the comments into a documentation clarification which got resolved, which ended up responsible for closing the issue, but in the end, the 'oauth2 client credentials grant type' feature is still missing, hence the feature request should remain open, but I guess current issue is now the official tracker for such feature, and it seems like so since I see from the above it was added to the Prioritized Product Backlog, so if that's the case, great news)

For the record, the lack of this feature would prevent me from migrating a multi-tenants use case from keycloak to zitadel, since just too many tenants rely on oauth2 client credentials method, to access non-interactive/service-to-service protected REST APIs. I understand the alternative option of using the JWT PKCE option, but in the case of a multi-tenants situation, having to migrate multiple customers at once from using client credentials with client/secret to using client credentials with signed jwt is not trivial/fun, in some cases, perhaps even not an option for some tenants.

I'll be watching this issue/FR, thanks!

Stay keen, if I am not wrong, we plan to work on this in the sprint starting next week 😁

**Comment by Frank-D** [comment]
Ohh, awesome news, thanks @fforootd ;-) 

Do you know if provisioning (e.g. creation) of those [service accounts with client credentials access] using one of your admin rest api will be part of the story definition (...apart from being able to do it manually over zitadel's console/dashboard UI), to allow using zitadel in headless mode for this client credentials scenario as well? 

I'm asking this, because in my case, I wasn't planning on exposing the [IAM tool]'s UI to the tenants/customers, but rather, exposing only my own UI with only the functionalities that I want to be exposed for them, and this includes only a limited set of IAM functionalities of such selected IAM tool (keycloak, or zitadel perhaps;-)) that is needed in the context of my app, rather than exposing them everything/unnecessary functionalities offered by the IAM tool that my app isn't using and confuse them.

This means, my management UI app would be calling my management backend app, which in turn would be responsible for calling the IAM tool's management APIs securely for the needed tasks (~headless mode), such as, provisioning service accounts, so that a tenant/customer could use my app UI to get a service account created, and in turn, my backend would call in this case zitadel's admin api to get the service account created dynamically, and then I could display back to the tenant/customer through my management UI app their generated [client credentials's] secret (alongside their client id, token and [optionally] refresh token endpoints), if properly returned by that said zitadel admin API. 

Is that the idea to be supported? : )

**Comment by fforootd** [comment]
Hey  @Frank-D 

Actually what intend to do is exactly how we think zitadel should be used.

So in short, yes there will be an api to manage that, since we follow an api-first approach (even our own management GUI called Console is using our API all the time)

**Comment by Frank-D** [comment]
Any link with current request and https://github.com/zitadel/oidc/pull/172?

**Comment by fforootd** [comment]
> Any link with current request and [zitadel/oidc#172](https://github.com/zitadel/oidc/pull/172)?

The lib supports it but the implementation in ZITADEL is not yet done.

**Comment by mffap** [comment]
@livio-a or @dakshitha could you please check the discussions / discord for users who asked for this and provide an update? Thanks.

I've linked two of the discussions above: https://github.com/zitadel/zitadel/issues/4211#issuecomment-1284148247
