### ISSUE TITLE
SMTP Config not saved

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4215]
**Describe the bug**
When ZITADEL is started without an SMTP config it is not possible to save one through the API or GUI.

**To Reproduce**
1. Start a ZITADEL e.g with the compose example
2. Try to store a SMTP config
3. Wait a few seconds and refresh the page

**Expected behavior**
The SMTP Settings should be persisted

**Additional context**
[Discord Reported](https://discord.com/channels/927474939156643850/927866013545025566/1009534676999864401)

**Comment by fforootd** [comment]
CC @livio-a

**Comment by livio-a** [comment]
I'll check today

**Comment by livio-a** [comment]
Already found the issue:
Console does not handle the error returned from the API: `The sender address must be configured as custom domain on the instance. (INST-83nl8)`

The error is thrown because of this setting:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/9405495/185305774-44fa6f9e-68cf-43e2-bd3e-43a62a7818f7.png">

The intention was to restrict the sender address to the domain of the instance to have the trust anchor beyond the UI and into the communication channels. See https://github.com/zitadel/zitadel/issues/3359

But does this even make sense... does ZITADEL have to check this or is it just the SMTP (relay) job if the sender name / address is allowed to send as such?

@fforootd any opinion?

**Comment by fforootd** [comment]
Hm, good question. As long as the SMTP config stays on the instance it don't see too much benefit of doing the security there.

I think it is more relevant to #3966 

Also this is somewhat influenced in Zitadel.cloud since customers need to have a custom domain to send mail from that domain to decrease abuse.

**Comment by fforootd** [comment]
Since there is a workaround we lower the prio to medium

**Comment by fforootd** [comment]
After giving it some thought and consideration of #4245 @livio-a and I came to the following conclusion

## Action Items

- [ ] Change the default behaviour of "SMTP Sender Address matches Instance Domain" to OFF (aka change the defaults yaml) @livio-a 
- [ ] Frontend need to handle the error of this settings is on @peintnermax
