### ISSUE TITLE
Userdata is invalid (COMMAND-Dfd21) - Can't create any user

### ISSUE THREAD

**Issue by droslean** [zitadel/zitadel#4220]
When trying to create a user, I get this error:
```
Userdata is invalid (COMMAND-Dfd21)
```

**To Reproduce**
1. Go to 'Users'
2. Click on 'New'
3. Add any user details

**Expected behavior**
The user should have been created.

**Screenshots**
![image](https://user-images.githubusercontent.com/8650912/185787106-bd7d9e8c-3e4a-45fe-a044-1f2dfa4d0b2f.png)

**Version**
2.1.1

**Comment by livio-a** [comment]
Hey @droslean 

I think I know what the problem is. Can you confirm that the "User Loginname must contain orgdomain" in the "Domain Settings" on your organization or on the instance is not activated?

ZITADEL currently always expects loginnames to be in an email format.
By default this is `<username>@<org-domain>`. Like that usernames (specified in the create dialog) are unique within an organisation.
If the setting mentioned above is disabled, the username will not be suffixed by the org-domain. Currently we still check for an email style name as we used to take the email address as username in such cases. There's an issue / PR work in progress to solve this: https://github.com/zitadel/zitadel/issues/4052

**Comment by droslean** [comment]
@livio-a I can confirm that the problem is related to what you describe in your comment. 

Closing this issue as duplicated to https://github.com/zitadel/zitadel/issues/4052
