### ISSUE TITLE
Additional languages for login and self-service

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4244]
The following languages were requested by users of ZITADEL: 

- [x] Polish
- [x] #5585 
- [x] Czech
- [ ] Danish
- [x] Swedish
- [x] Dutch
- [ ] Norwegian
- [x] #4222 
- [x] Portuguese
- [x] #3990 

Considerations
- These languages should be available to end-users (not admins); relates to #4233 
- We might want to lint/automatize checking for keys in i18n files

**Comment by fforootd** [comment]
you forgot Portuguese

**Comment by honzapatCZ** [comment]
I'd add the need for default translations being instead of "Finish initializing account at Zitadel" to "Finish initializing account at <BrandName>". Its not fun to go thru x languages and x texts.

What about being able to disable certain languages. Ie you want more customized texts(maybe a legal need to disclose some stuff on registration?), but dont have the personnel to localize 20x languages?

Lastly what about supporting arbitrary languages? Ie admin defined?

**Comment by AngeloBestetti** [comment]
> you forgot Portuguese

Portuguese from Brazil too, "pt-br"

**Comment by hifabienne** [comment]
I will close this issue as we have most of those languages implemented.
If we see a need for a language we will create a dedicated issue for it
