### ISSUE TITLE
Console: Users should land on the Instance Level first

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4298]
Managers of ZITADEL should generally land first on the Instance level. This is especially true on first use.

As user I would expect to work my way down from global default settings and setup to the settings and configurations of objects that are in a lower hierarchy.

This would make start much more intuitive and I can jump directly to the organization that I want from the organization list.

Considerations:
- Exception for personal profile and such
- Maybe there's a way to specify which organization should be shown after login (like a primary domain scope)

**Acceptance criteria**
- [ ] ...
- [ ] ...

**Comment by hifabienne** [comment]
With #4835 we will implement kind of a first tasks list.
In my opinion it should start with creating a project and application to be able to make a login to the own application as soon as possible. This would disagree with the issue here, since it would be the first action directly in an organization.
After the first project and app are setup, I think we should configure the instance settings.

@mffap is it ok if I close this issue and we focus on the #4835

**Comment by mffap** [comment]
> With #4835 we will implement kind of a first tasks list. In my opinion it should start with creating a project and application to be able to make a login to the own application as soon as possible. This would disagree with the issue here, since it would be the first action directly in an organization. After the first project and app are setup, I think we should configure the instance settings.
> 
> @mffap is it ok if I close this issue and we focus on the #4835

Sure, makes sense. Still, the hierarchy could be handled in a better way.
