### ISSUE TITLE
zitadel requires admin privileges to initialize the database.

### ISSUE THREAD

**Issue by lordwelch** [zitadel/zitadel#4304]
**Describe the bug**
zitadel requires admin privileges to initialize the database.

**To Reproduce**
1. login to DB
2. `CREATE ROLE zitadel WITH LOGIN PASSWORD 'password';`
3. `CREATE DATABASE zitadel OWNER zitadel;`
4. Apply database config
  ```python
Database:
  cockroach:
    Host: 'cockroachdb'
    Database: zitadel
    User:
      Username: 'zitadel'
      Password: 'password'
    Admin:
      Username: 'zitadel'
      Password: 'password'
```
```console
time="2022-09-04T06:16:48Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:75"
time="2022-09-04T06:16:49Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel
time="2022-09-04T06:16:49Z" level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:68" error="ERROR: user zitadel does not have CREATEROLE privilege (SQLSTATE 42501)"

```

**Expected behavior**
Initialization succeeds without a privileged user.

**Additional context**
If initialization starts at `04_eventstore.sql` a privileged user is not needed

**Comment by adlerhurst** [comment]
Hello @lordwelch 

If you want ZITADEL to start from file 04 please use the following commands:

1. `zitadel init zitadel`: to execute the sql statements to init the database with a non privileged user, the first 3 statements have to be executed manually.
2. `zitadel start-from-setup`: verifies data migrations (e.g. during version changes) and starts zitadel afterwards.

Here is an example docker compose using postgres instead of cockroach:

- docker-compose.yaml: [docker-compose-example.yaml.txt](https://github.com/zitadel/zitadel/files/9491632/docker-compose-example.yaml.txt)
- ini.sql: [init.sql.txt](https://github.com/zitadel/zitadel/files/9491634/init.sql.txt)

**Comment by lordwelch** [comment]
@adlerhurst Thank you this worked perfectly

**Comment by nimbusss2000** [comment]
Hello! I have a similar issue, only I'm running zitadel in kubernetes. Please tell me how can I skip the first 3 statements that require admin rights?
