### ISSUE TITLE
Extend Console to configure idp based on templates

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4433]
As a zitadel admin i want to be able to enable/disable identity providers and add some needed configuration based on the provider, so I do not have to know all information of a provider.

**Acceptance Criteria**
- [x] All possible providers are shown on the instance and organisation level
- [x] I can enable a new provider and have to add the needed information (e.b. client id, secret) on enabling
- [x] I can disable an enabled provider
- [ ] I am able to upload a picture to the generic provider
- [x] The specific providers do show a logo that is pre configured

**Comment by hifabienne** [comment]
@juergrinaldi can you please make a design for this

**Comment by juergrinaldi** [comment]
![01-idp-start](https://user-images.githubusercontent.com/48990649/212875176-3b326095-cace-4d73-b7f0-ad3b747f08a6.png)
1. List shows already set up IDPs. If there are none, only the selection part below is showing.
2. Thought it would be helpful if users can submit wanted IDPs, so we can provide according to demand.


![01b-idp-start](https://user-images.githubusercontent.com/48990649/212875181-c2ef5cb3-701d-40fb-87c7-b322d292a760.png)


![03-idp-step1](https://user-images.githubusercontent.com/48990649/212875183-842f8366-bf81-466a-b962-641519f4579f.png)
3. this step should include all data/inputs that are generally used within all selected IDPs.
4. we should pre-fill as many defaults as possible/viable through all of the steps.


![04-idp-step2](https://user-images.githubusercontent.com/48990649/212875184-cd9273d9-64d2-480d-977a-4e0258a145b2.png)
5. following the previous screen are specific data for the selected IDPs. Each with an own step.
6. IF we want to include custom data mapping and/or show how the default mapping is, we should show this on a separate screen.


![05-idp-step3](https://user-images.githubusercontent.com/48990649/212875185-b7210eab-7e8e-4c23-b6e2-642bfd11d455.png)
7. Because there can be a lot of attributes/permissions they are collapsable (but it probably make sense to show them per default).


![06-idp-end](https://user-images.githubusercontent.com/48990649/212875188-77f90d44-06aa-46f3-a022-e4a4f7fced27.png)
8. after setting up your IDPs you land back at the starting page with all new IDPs "active/available" per default. via click on the icon you can deactivate it. (if it's critical we can show a 'are you sure?' prompt)
9. on hover we show a delete option. on click on the whole row we show the complete list of data/options for that IDP.
10. here is shown a reduced list of IDPs, according to the already set up ones, to reduce clutter. If users need to be able to set up multiple of the same IDP, the list will stay complete.

**Comment by juergrinaldi** [comment]
@hifabienne @livio-a I added my first draft, can you check if that is viable?

**Comment by hifabienne** [comment]
Looks good to me

**Comment by mffap** [comment]
The designs look great 👍 Also like the improvement of the active state!

**Comment by peintnermax** [comment]
Last missing piece will be addressed seperately #5455
