### ISSUE TITLE
"Send new initialization email" with wrong SMTP config fails silently

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4548]
**Describe the bug**
Adding a new human user (or simply sending a new initialization email) having the wrong SMTP user succeeds, even though no email is sent.

I don't know the details of SMTP integrations, it could also be that the SMTP provider is asynchronous.

**To Reproduce**
1. Change SMTP user from `zitadel@caos.ch` to something else
2. Go to a user and click on "Send new initialization email"
3. Successful response, but no email is sent

**Expected behavior**
The request should fail

**Additional context**
ZITADEL Cloud 2.8.2

**Comment by hifabienne** [comment]
Hi @DavideWalder 
Thanks for your report.
Yes the send email is asynchronous, so we are not able to send you a direct error message.
But we know that at least you should get some how a feedback that there was an error.
We have already created an issue for the smtp problematic: #4504 
Also because at the moment it is not possible to send a test email for a new smtp provider

**Comment by DavideWalder** [comment]
@hifabienne Thanks for the explanation, I'll close the issue
