### ISSUE TITLE
LDAP Login

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4609]
As an end user I want to be able to login with my user of an LDAP, so I can use my existing user and do not have to create a new one.

**Acceptance criteria**
- [ ] I am able to login with my LDAP user
- [ ] If my user doesn't exist in ZITADEL I have just in time provisioning
- [ ] UI to be able to enter the ldap user credentials (should look like our own login just with username and password)

**Additional Context**
- All external Authentication Actions should work as before

required #5068

**Comment by hifabienne** [comment]
From our side we will implement this preferable after #4431 
But it will be possible before.
It takes us about 3 weeks to implement

**Comment by helmut72** [comment]
> Just in time provisioning

Would be cool to read `jpegPhoto` from LDAP to provision the profile picture in Zitadel. Thanks :)

**Comment by overpod** [comment]
I really need this opportunity. Your product is wonderful. Ready to test this feature

**Comment by dracowf** [comment]
Happy new year! 🎉 Can you give us any estimations or roadmap when we can expect this feature on? :)

**Comment by fforootd** [comment]
We are currently considering this feature but there is no ETA yet. @hifabienne can shine more light into this.

**Comment by stebenz** [comment]
As we are currently in the progress of implementing this functionality, we got some feedback that would change your initial basic configuration. Still, before we change everything I would be pleased about some input from all interested.

Our suggestion:
- host, used with port to create the URL to connect "ldap://host:port"
- port
- tls, bool to define if a TLS should be used when connecting to the LDAP server
- baseDN, base of the user
- userObjectClass,  objectClass which the user has to have and is used to search for the DN of the user
- userUniqueAttribute, attribute which has to be unique on the LDAP and is the "loginname" in the GUI on ZITADEL side
- admin, user which has to have at least read permission to search for the userbind
- password, for the admin user to login
- attributes, struct to define attributes which are used to fill in the information on ZITADEL side

Proposed changes on the configuration:
- servers, ordered list of servers to try with the bind, for HA szenarios, replaces host, port and tls
- baseDN, base of the user
- bindDN, bind to use when search for the user, rename of admin
- bindPassword, rename of password
- userBase, new,  current default "dn", should then be configurable
- userObjectClasses, rename of userObjectClass, list instead of single class which is required
- userFilter, rename of userUniqueAttribute, list of attributes which are "OR" connected to search for the user, instead of single attribute that has to be unique, so that for example the user has the option to either use the username or the email to login
- timeout, timeout for the connection with the LDAP server
- (certificates), this should not be configurable through the API, but should suffice when you add the trusted certificates in the container so that also connections with private CAs are possible

Some changes are just renames, but some changes have some implications don't the logic and how you have to handle the users in the LDAP server.
I just marked all who reacted on the issue, so feel free to give a comment on our suggestion and on the proposed changes.

@pr0gr8mm3r @helmut72 @LeonDevLifeLog @supapo @bman46 @dracowf @nicusoru @adamphetamine @overpod @strobeltobias

**Comment by dracowf** [comment]
Asked a colleague who will be doing the Zitadel integration to look at the thread. In general, everything looks valid, the rest we can say only after the integration and tests.

**Comment by helmut72** [comment]
Looks good for now. Need to be tested. ;)

What TLS will be supported? TLS on TCP port 636 and/or STARTTLS on TCP port 389?

> attributes, struct to define attributes which are used to fill in the information on ZITADEL side

Is there a list of possible attributes available?

**Comment by joostmacantanl** [comment]
Will AD LDS be supported?

**Comment by stebenz** [comment]
@helmut72 
> Looks good for now. Need to be tested. ;)
> 
> What TLS will be supported? TLS on TCP port 636 and/or STARTTLS on TCP port 389?
> 
> > attributes, struct to define attributes which are used to fill in the information on ZITADEL side
> 
> Is there a list of possible attributes available?

Good input, will add a startTLS attribute to cover all 3 possibilities with TLS, startTLS and non-TLS, port is covered in the servers attribute.

All the attributes used to create the user:
- 	idAttribute
- 	firstNameAttribute
- 	lastNameAttribute
- 	displayNameAttribute
- 	nickNameAttribute
- 	preferredUsernameAttribute
- 	emailAttribute 
- 	emailVerifiedAttribute, has to be convertible to boolean
- 	phoneAttribute 
- 	phoneVerifiedAttribute, has to be convertible to boolean
- 	preferredLanguageAttribute, has to be convertible to language
- 	avatarURLAttribute
- 	profileAttribute

**Comment by stebenz** [comment]
@joostmacantanl 

> Will AD LDS be supported?

As we understand the differences between AD LDS and LDAP we should support it, as it is only limited to authentication(binds) there should be no problem.
