### ISSUE TITLE
New Admin could not work with instance

### ISSUE THREAD

**Issue by pflegende** [zitadel/zitadel#4637]
**Describe the bug**
try to open instance. But next step not available. Only again NewUser workflow appears.

**To Reproduce**
1. Go to dashboard with instances. 1 instance is listed. = ok
2. Click on 'arrow right on top' (of the listed instanc)
3. See error
it apears the first window of new user dialog after recieving a mail (but it was completed before)

**Expected behavior**
expect a window, may be some dashboard, to work with the new instance

**Screenshots**
![Opera Momentaufnahme_2022-10-30_045637_zitadel cloud](https://user-images.githubusercontent.com/52720420/198862149-5e2b8eb4-a7f8-4b64-b605-4216feebdf44.png)
![Opera Momentaufnahme_2022-10-30_050123_pflegende-eksknd zitadel cloud](https://user-images.githubusercontent.com/52720420/198862151-1369a40a-30c0-4465-90ff-26b9840b1eb2.png)
![Opera Momentaufnahme_2022-10-30_050518_pflegende-eksknd zitadel cloud](https://user-images.githubusercontent.com/52720420/198862152-e4311abb-ba30-43eb-aab0-64be3bc5dc93.png)

**Desktop (please complete the following information):**
 - OS: w7
 - Browser opera
 - Version newest , account generated today `<html>
<body>

2022/10/30 04:14am | Initialize User for Customer Portal
-- | --

<br class="Apple-interchange-newline">
</body>
</html>

**Smartphone (please complete the following information):**
 - Version [e.g. 22]  `2022/10/30 04:14am	[Initialize User for Customer Portal]`

**Additional context**
nothing

**Comment by mffap** [comment]
Hi @pflegende when creating a new instance you should get an email with the credentials at the moment. You can sign into your instance with these credentials and will land in the Console, where you can manage everything. The flow is at the moment not very intuitive, we are currently working on improving this in various ways (signup with email, sso to instances etc..). Let me know if you could login with the information in the mail.

@hifabienne I experienced the loading time as described here as well on opening the console, since a couple of weeks actually. We should check that.

**Comment by mffap** [comment]
@pflegende we did several changes over the last few days to improve performance. That should solve the issues around the console. Could you please check, if it works ok for you?
I'm closing this issue for now. Please feel free to re-open, if the issue persists for you.
