### ISSUE TITLE
Use system config for OTP name

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4712]
As an end user of ZITADEL I want to be able to see for which system I have configured OTP and not that is is ZITADEL, because most of the time I do not know what ZITADEL is.

**Acceptance criteria**
- [ ] When I configure a new OTP I do not see ZITADEL somwhere
- [ ] When I add a new OTP I see the requested instance domain as "name" (take it from the instance context)

**Additional Context**
At the moment this is set in the default settings of ZITADEL and we always take it from there

**Comment by eliobischof** [comment]
@bitfactory-sem-denbroeder tries to implement it:  https://discord.com/channels/927474939156643850/927866013545025566/1093486282677690450

**Comment by bitfactory-sem-denbroeder** [comment]
Might be nice to be able to overwrite this behavior with an ENV var, so that if you for whatever reason don't want to use the instance URL you can just set up whatever name you want.

**Comment by eliobischof** [comment]
I thing we should [default this existing config (ZITADEL_SYSTEMDEFAULTS_MULTIFACTORS_OTP_ISSUER)](https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml#L322) to the empty string and use it if it's defined, otherwise use the current users host.

Not sure if we still should default to ZITADEL so we don't break the behaviour. Opinions, @zitadel/engineers?

**Comment by bitfactory-sem-denbroeder** [comment]
Missed this comment before adding my first commit, apologies. Added a check to see if its defined and if not default to the exteralURL
