### ISSUE TITLE
Custom attributes in SAML response

### ISSUE THREAD

**Issue by stebenz** [zitadel/zitadel#5014]
As an administrator, I want to be able to define custom attributes in the SAML response so that I can connect more service providers to ZITADEL, which for example needs the roles of the user.
(called custom claims in OIDC)

**Acceptance criteria**
- [x] SAML responses can be extended with additional attributes
- [x] SAML responses can be modified/extended through actions
- [x] SAML responses can be modified/extended with attributes of different types and names
- [ ] Add Documentation how to do it

**Comment by binaryfire** [comment]
Would love to see this implemented. It’s the only thing stopping us switching from Keycloak to Zitadel in production. KC’s SAML mappers are essential for integrating with some third party services.

**Comment by sakazuki** [comment]
I need this feature to use zitadel for Amazon Grafana SAML auth.
I think Actions is one flexible way to solve  this request.

**Comment by adamphetamine** [comment]
Ability to map SAML attributes seems to be a requirements for Mosyle MDM-

3) Map the attributes expected by Mosyle to values in your Identity Provider

userfullname = Username, etc.
uid = Username, User ID, Email Prefix, etc.
mail = Email, etc.

**Comment by livio-a** [comment]
Another example of mapping roles / groups: https://github.com/zitadel/zitadel/discussions/5872

**Comment by adamphetamine** [comment]
I've just discovered that my big project fails due to these missing attributes- I mistakenly thought the tick box for 'Assert roles on authentication' was my answer, but I should have known this from earlier efforts.

Here's another great article showing how to add roles/ groups to Azure AD -
https://sada.blog/Group-in-SAML-to-SAP/

And here's AWS notes on the Role attribute
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html

I hope this helps

**Comment by BellCon** [comment]
Would also really love to see this implemented.  OpenVPN cloud relies on the attributes being mapped to assign users to security groups for access levels.  Unfortunately they don't support OIDC, only SAML or AD.

We're looking at migrating our clients across from OneLogin (which does have this feature) but ideally we need this implemented first.

Please and thanks!
