### ISSUE TITLE
API: Register Username Password

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5017]
As a developer, I want to be able to register my users with username and password through an API, so that I can build my custom registration UI.

**Acceptance criteria
- [ ] I am able to register a user with username password
- [ ] I am able to register a user with the profile data
- [ ] I am able to register a user with email
- [ ] I am able to register a user with metadata
- [ ] Check permission

**Additional Information**
- Changing parts at the current implementation, not writing it new
- Use prepare functions

**Comment by dakshitha** [comment]
Request on Discord (from MeeMee) - 

Is there a way of getting the registration link after registering a humanUser via the management API, instead of sending out an email automatically? We want to send out the mail via our own API. We need to customize our invitation mail based on the company that invited an user.  (dynamic image, company name... etc...)
