### ISSUE TITLE
Should Post Authentication Actions Just Run Once? 

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5040]
Follow-up issue of #4982

With the implementation of #4982, when a user authenticates successfully via OTP, the post authentication action run once when password is successfully vailidated and once, when the OTP is vaidated successfully. The same goes for U2F and also passwordless.

Is this behaviour intended?

**Comment by hifabienne** [comment]
Not sure if I understand it correctly. The Action should run when the user is authenticated

**Comment by hifabienne** [comment]
I think if this happens the implementation of #4982 is wrong.
I want to be able to trigger something post authentication not post orp and post password check. 
So if I implement something post authentication e.g log successful login to stdout, that this is only logged once. otherwise I would think the user has successfully authenticated twice

**Comment by hifabienne** [comment]
Discussed with elio. Will close this issue for now as it is not relevant
