### ISSUE TITLE
e2e tests for actions

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5097]
As a ZITADEL developer, I want to be able to use the e2e tests to tests the actions during login so that I can verify the proper working of Actions automatically.

**Acceptance criteria**
- [ ] e2e tests for actions are possible
- [ ] Test should test if actions are executed on local authentication
- [ ] Test should test if metadata can be added to local user
- [ ] action on user name password should be tested
- [ ] action on otp authentication should be tested
- [ ] action on u2f authentication should be tested
- [ ] action on passwordless should be tested

**additional information**
at the moment it is only implemented to test on chrome, this can be configured

**Comment by eliobischof** [comment]
@hifabienne can we take this into the next sprint?

It would improve quality assurance a lot with little effort.
The hard work is already done, but the longer we wait, the more conflicts arise.

**Comment by eliobischof** [comment]
@hifabienne, prioritizing this one higher than https://github.com/zitadel/zitadel/issues/4532 is more efficient, because there is a lot of simplifying refactoring already done for the actions tests which will help implementing https://github.com/zitadel/zitadel/issues/4532.
For example:
- Org isolation
- Test setup
- Testing with OTP
- Testing with U2F
- Testing with Passwordless

**Comment by hifabienne** [comment]
I will close this issue, as our new actions work differently, if we need it we will reopen
