### ISSUE TITLE
[Bug]: claims of scopes are missing in the JWT token for service users

### ISSUE THREAD

**Issue by demircis** [zitadel/zitadel#5266]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When getting an access token via the token endpoint as described in [Zitadel docs](https://zitadel.com/docs/apis/openidoauth/endpoints#client-credentials-grant) using grant type `client_credentials`, the returned access token is missing several claims of the passed scopes.

In my example, I pass scopes `openid profile email urn:zitadel:iam:user:metadata urn:zitadel:iam:org:id:project:roles` in the request body, but only the metadata is present in the token payload.

### To reproduce

1. Create a service user with the token type JWT
2. Generate client credentials for the service user
3. Send a request to the token endpoint with the credentials as described in the documentation linked and the scopes specified above
4. Decode the returned access token to see if the correct information is returned in the token payload

### Screenshots

![Screenshot 2023-02-22 at 10 47 15](https://user-images.githubusercontent.com/22999224/220584590-60fd2b90-d87a-46c9-a8ed-fce0a37da07f.png)
![Screenshot 2023-02-22 at 10 49 12](https://user-images.githubusercontent.com/22999224/220584603-ed4aabb6-d5c9-45d3-94a2-86b740e5b863.png)

### Expected behavior

I expect to find the claims included in the scopes that are passed in the body of the token endpoint request. In our case, the service user has a role `user` for example, which is missing in the payload.

### Version

2.20.0

### Additional Context

In the Zitadel console, we set to send the roles when authorizing:

![image](https://user-images.githubusercontent.com/22999224/220585427-b59e79ea-0c18-44cf-9447-6cc312c1bc21.png)

**Comment by hifabienne** [comment]
Hei @demircis 
I think there are different problems why it is not included in the token.
profile & email: a service account does not have a profile and and email, so it doesn't make sense to request those scopes and it will not be included in the token
Roles scope: The scope you are sending does not look correct. You have to request the roles you want to include: urn:zitadel:iam:org:project:role:{rolekey}
Scopes: https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes

But I was also not able to request the roles with the correct roles, with opaque tokens it should work. We have to investigate more on our side.

**Comment by TakumiHaruta** [comment]
The same issue is here as well. It's nice to have `AUTHTOKEN OPTIONS` for `PRIVATE_KEY_JWT` app to add a role info of the service user into access token;

<img width="1022" alt="Screenshot 2023-03-01 at 16 30 44" src="https://user-images.githubusercontent.com/35373297/222073038-3d844520-911e-4aa0-a929-bd4e97aae3df.png">

Current token;

```
{
  "iss": "https://example.com",
  "sub": "2021xxxx",
  "aud": [
    "https://example.com",
    "2021xxxx"
  ],
  "jti": "2032xxxx",
  "exp": 1677698902,
  "iat": 1677655702,
  "nbf": 1677655702,
  "urn:zitadel:iam:user:metadata": {
    ....,
  },
  "urn:zitadel:iam:user:resourceowner:id": "2021xxxx",
  "urn:zitadel:iam:user:resourceowner:name": "xxx",
  "urn:zitadel:iam:user:resourceowner:primary_domain": "xxx.example.com"
}
```

Expected token;

```
{
  "iss": "https://example.com",
  "sub": "2021xxxx",
  "aud": [
    "https://example.com",
    "2021xxxx"
  ],
  "jti": "2032xxxx",
  "exp": 1677698902,
  "iat": 1677655702,
  "nbf": 1677655702,
  "urn:zitadel:iam:org:project:roles": {
    "rolekey": {
      "2021xxxx": "xxxx"
    }
  },
  "urn:zitadel:iam:user:metadata": {
    ....,
  },
  "urn:zitadel:iam:user:resourceowner:id": "2021xxxx",
  "urn:zitadel:iam:user:resourceowner:name": "xxx",
  "urn:zitadel:iam:user:resourceowner:primary_domain": "xxx.example.com"
}
```

**Comment by demircis** [comment]
Hi @hifabienne, is there any update on this issue? This is a blocking issue for us as we rely on the roles being returned in the token.

**Comment by livio-a** [comment]
Hey @demircis 

I had a look at it and the problem regarding roles in tokens for service account is the following:
Unlike a human user, service accounts do not authenticate using a client. So context information is missing (where does the role belong to). With human users, the client provides the context (project) where the roles need to be checked.
Service accounts using opaque tokens don't have this problem, because the token has to be introspected to get the information, which gives us the context again.

One possible solution would be to take the audience as context (for requested roles).
I guess this would solve your problem, right?

We still check two points in this regard:
- Currently only roles of the authorized client / project can be requested. Do we leek information if we extend it to the audience (any client / project)? <- @fforootd do you see a problem in that?
- How to handle if multiple projects share the same role key? If we keep the current claims schema, this could lead to broken authorization. To be on the safe side / assert it properly in the claims, we would add a claim for each project:
```
"urn:zitadel:iam:org:project:id1:roles": {
    "rolekey": {
      "2021xxxx": "xxxx"
    }
  },
  "urn:zitadel:iam:org:project:id2:roles": {
    "rolekey": {
      "2021xxxx": "xxxx"
    },
    "rolekey2": {
      "2021xxxx": "xxxx"
    }
  },
```

We would then need to check if tokens of human users / returned from a code flow could use this mechanism as well or if we at least would assert an additional claim with the projectID:
```
"urn:zitadel:iam:org:project:roles": {
    "rolekey": {
      "2021xxxx": "xxxx"
    }
  },
"urn:zitadel:iam:org:project:id1:roles": {
    "rolekey": {
      "2021xxxx": "xxxx"
    }
  },
```
so there's the possibility to always check the roles on a projectID claim (regardless if service user or human).

I hope this is somehow understandable.

**Comment by demircis** [comment]
Hi @livio-a 

Thank you for looking into it. If I understood correctly, you are planning to add new claims of the form "urn:zitadel:iam:org:project:{projectid}:roles" which list the roles for service users given the project ID as the context, right?

Would there be a corresponding scope that includes these claims? Or how would we then obtain the roles with this new change?

**Comment by livio-a** [comment]
Hey @demircis 

Exactly, we would use the project ID as context in the claims.

Regarding the corresponding scope:
Currently the only scope possible to request is `urn:zitadel:iam:org:project:role:{rolekey}`, where you would need to request every role separately. This makes sense in some cases, but there's currently no possibilty (for service users) to assert all roles.
We would therefore create a new scope, e.g. `urn:zitadel:iam:org:project:roles`.And additionally this will not only include all roles of the project itself, but of all projects in the audience (requested by the audience scope).
