### ISSUE TITLE
[Bug]: Saving without change in STMP settings results in error message

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5612]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When saving without changing anything this error occurs too. 

`No changes (COMMAND-m0o3f)`

This should be avoided, as it might be confusing to the user that something went wrong. 

### To reproduce

Go to Settings > Notification Settings
Click Save button without changing anything.

### Screenshots

![image](https://user-images.githubusercontent.com/48990649/230037835-e434f040-ee38-44d7-917a-57f52e7d96e3.png)

### Expected behavior

There are two valid behaviors to this:

a) Let them save as much as they want. Only show an error when it couldn't be saved.
or
**b) Disable the Save button until some changes have been made.** (<- preferred)

### Operating System

Mac/Windows
Chrome

### Additional Context

- *IF* there is a valid error message, it should be better readable
- I also got this error when I actually _changed_ the sender name, but I couldn't reproduce, so I didn't made a separate issue. But might be somthing to look out for.

**Comment by hifabienne** [comment]
Hei @juergrinaldi 
This is something that happens on all ZITADEL resources the error is coming from the backend.
If we want to avoid that we would either have to change the logic of ZITADEL so no changes just return ok or change the frontend so you cant save when there are no changes.

@zitadel/engineers What are your opinions? Would it be better to send ok instead of an error when we do have no changes? I guess that would be a breaking change? maybe something to consider when we start with the new api?

**Comment by adlerhurst** [comment]
I Would return an ok in the new api version because the changes a user wanted to make are stored.

**Comment by livio-a** [comment]
> I Would return an ok in the new api version because the changes a user wanted to make are stored.

totally agree on that. we plan to do so (like we already did with idp templates)
relates #5015

**Comment by hifabienne** [comment]
I will put this issue to product backlog, as it will change with the new ressource based api

**Comment by hifabienne** [comment]
I change the issue, as it is not a bug, and we will change that behaviour in the new api.
