### ISSUE TITLE
Change request (UX based): Only use one save button in STMP Settings

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5613]
Right now, there are two - completely separated - Save buttons on the SMTP Settings page.

![image](https://user-images.githubusercontent.com/48990649/230041417-7a9f2514-7ea3-4d58-9b63-509854b24b4b.png)

This is *very* confusing for the user, as they might get the impression that these are linked (one top, one bottom).
For example: If a user changes the _Sender Email Address_ they might be tempted to click on the button above (rule of proximity) 

Expected: One Save button for the whole page or keep multiple but have them linked (usually on very long pages). (I prefer the first approach of these two.

even better alternative: Have a fly-in/toast message that shows you the save button no matter where on the page you're at, similar to this:

<img width="721" alt="image" src="https://user-images.githubusercontent.com/48990649/230043052-b7feb8ca-ae23-4afe-af65-1436fe36dacc.png">

This one would need some general approach on the whole saving system on the whole ZITADEL/Console though.

**Comment by hifabienne** [comment]
@juergrinaldi I think why it is currently implemented like this, because this are two independent settings.

The first is about setting your notification preferences (where should the users get some notifications), its strange because its only one attribute at the moment, but i guess this will be extended at one point.

The second is the notification provider, how the messages should be sent.

Just some thoughts:
Would it make sense to state that more clear?
Would it make sense to separate them, maybe Notification Preferences and Notification Provider?
Or is it the best to have them on one page with one save button?

**Comment by juergrinaldi** [comment]
> Just some thoughts: Would it make sense to state that more clear? 
I don't think that it feasable (or easily done). (not recommended)


> Would it make sense to separate them, maybe Notification Preferences and Notification Provider? 
> Or is it the best to have them on one page with one save button?

Either is fine with me. Currently I'd go with the latter but it can also change over time if the page gets more complex with more options.

**Comment by hifabienne** [comment]
We have decided to split the configurations and make 3 sidemenu points in the notifications

Messages
- Notifications
- SMTP Provider
- SMS/Phone Provider

**Comment by doncicuto** [comment]
@hifabienne, I'm working on this issue if you could assign it to me

![image](https://github.com/zitadel/zitadel/assets/30386061/c432f28e-72dc-48c7-8ab2-b29f01652d26)
