### ISSUE TITLE
[Bug]: migration already started, at step 10_correct_creation_date

### ISSUE THREAD

**Issue by verymilan** [zitadel/zitadel#5758]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

Hi there, I have just tried to update to v2.25.3 but Zitadel does not come up again, instead it's stuck at `msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:76" migration step=10_correct_creation_date.` 
I have tried to update to one of those .4 releases from a few hours ago, since they mention step10, but sadly no luck - however they mention Postgres, but i went with Cockroach.

### To reproduce

1. download new binary
2. put in place
3. restart

### Version

v2.25.4

### Operating System

Debian GNU/Linux 11 (bullseye)

**Comment by hifabienne** [comment]
@eliobischof Can you help here?

**Comment by eliobischof** [comment]
@adlerhurst you are working on step 10, right?

**Comment by verymilan** [comment]
The silence makes me wonder whether something about my setup is special after all? Wasn't cockroach highlighted in the docs? Should i do efforts to migrate to postgres?
I did the mistake to not do an extra backup right before the update (which i accept as my personal fail) and i did not want to lose the new and already active accounts, so i currently have inaccessible applications. :(

**Comment by adlerhurst** [comment]
sorry for the late reply. We saw this problem of the migration and it will be fixed in the next release which is currently building, but we have to set the migration to failed manually so that zitadel retries the migration.

There are two solutions for your problem:
1. if you can't wait we can provide the sql statements to set the migration to failed manually
2. We are currently working on a additional cli command which can be used to set a migration to failed. We will release as soon as possible.

**Comment by verymilan** [comment]
Ah okey, i've suspected something like this. Doing this by hand wouldn't be an issue for me, but if it's more convinient for you and it will become available like this evening (cest), i suppose that few hours more make no difference at this point. 😅 
(i couldn't interpret a possible query from that pr yet)

**Comment by adlerhurst** [comment]
I will provide the statements if we don't manage to create a release until we finish work

**Comment by adlerhurst** [comment]
if i get the edit history of your comment right zitadel is currently stuck. Please follow the steps exactly because not doing so might bring the system into in a nonrecoverable state.

Please check if the following statement returns `system.migration.started`
`select event_type from eventstore.events where instance_id = '' order by event_sequence desc limit 1;`
*ONLY* if thats the case execute the following statement: `delete from eventstore.events where id = (select id from eventstore.events where instance_id = '' order by event_sequence desc limit 1);`
If thats not the case please let me know, we have to insert an event in that case an the statement gets a little bit more tricky.

**Comment by adlerhurst** [comment]
sorry i missed to add the remove of an additional value, i add the comment an additional comment asap

**Comment by adlerhurst** [comment]
1. the following statement should return exactly one row: `select * from eventstore.unique_constraints where unique_field = (select event_data->>'name' from eventstore.events where instance_id = '' order by event_sequence desc limit 1);`
2. **ONLY** if so: `delete from eventstore.unique_constraints where unique_field = (select event_data->>'name' from eventstore.events where instance_id = '' order by event_sequence desc limit 1);`

Please make sure to start zitadel using v2.25.5

**Comment by verymilan** [comment]
Thanks a ton for your effort, the instance is alive again! 🎉 

I have noticed a flood of `msg"="did not register manual reader" "error"="duplicate reader registration"` but i think thats unrelated. 

Thanks again!

**Comment by adlerhurst** [comment]
happy to help.

Yeah the next release should fix the log.

If I got it right you tested a prerelease. These release are not proven to work correctly and can cause problems. It's recommended to use releases provided by the `latest` or `stable` release channel: https://zitadel.com/docs/self-hosting/deploy/overview#releases

If you need fast and direct support from us we are open to discuss a contract, feel free to schedule a [discovery call](https://calendly.com/zitadel-mpa/zitadel).

**For future readers**: v2.26.0 introduces a new command `zitadel setup cleanup` which solves the problem.

**Comment by verymilan** [comment]
Oh i sure hope i did not test a prerelease - originally i was updating to `v2.25.3` when i got stuck.  :)
