### ISSUE TITLE
Improve authenticated requests usage query performance

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#6425]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Scaling with the current usage queries on each request is hard.

### Describe your ideal solution

As a user, I want my requests to be performant, also when I have quotas enabled and millions of access logs so that I have no performance issues when I scale my usage.

#### Acceptance Criteria
- [ ] The number of access logs doesn't impact the performance of requests.

### Environment

ZITADEL Cloud

### Additional Context

Suggested solution:

#### Create projection.quotas
- The current quota configuration is projected.

#### Create a sub-projection projection.quotas.usage_periods

- Fields: period_start, usage
- Provide a function like AddIncrementOrInsertCurrentUsageToTransaction(transaction, quota.Unit, int64). If the current period doesn't exist, it inserts it, else it increments its usage field.
- Provide a function CurrentUsage(quota.Unit) int64
- Maybe create an index on the usage periods sub-projection?

#### Use the new projection
- Call CurrentUsage(quota.Unit) int64 from interceptors
- Call AddIncrementOrInsertCurrentUsageToTransaction() from logstore debouncer. Use the same transaction to write access logs and to increment the quota usage.
- Also call AddIncrementOrInsertCurrentUsageToTransaction() if emitting logs is not debounced is used.

**Comment by adlerhurst** [comment]
as discussed with @eliobischof @fforootd 

Single transaction in debouncer is not required.
Debouncer writes data to the defined units of the usage periods. currently only authenticated requests
interceptor queries latest usage quotas and returns error if quota.limit < quota_usage.sum

follow up:

split access log and quota usage so that it's not required to write access logs to enforce quotas. it's currently hard coupled because quota is enforced using the access logs (timeseries query)
