### ISSUE TITLE
Console: Keep url path when switching organizations

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6464]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Given I'm allowed to see/manage multiple organizations, 
When I switch between organizations with the org switcher in Console, 
Then end up on the organization's main page

### Describe your ideal solution

Stay on the same path, at least for settings. I find myself jumping between different organizations to compare settings. It would be nice to keep the path (eg, /ui/console/org-settings?id=idp) at least for the resource "org-settings", when switching organizations.

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment]
I think this is implemented like this, because some urls are organisation specific and you can't open them in another organisation. 
Example for detail page of a user: /ui/console/users/{user-id}?id=general

@peintnermax what is your input on this? Would it be possible, to stay on the same url, whenever possible and only switch when the don't exist?
