### ISSUE TITLE
Quick start guide screenshots are out of date

### ISSUE THREAD

**Issue by jbvv1** [zitadel/zitadel#6465]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

As a new user, I want to see screenshots in the quick start guide that are up-to-date with the Zitadel Cloud UI. For example, the quick start guide mentions that the `userinfo_endpoint` is visible in the URLs page and shows a screenshot with the URL clearly visible, but as of 8/31/2023, this URL is no longer visible in the UI and needs to be fetched from the discovery endpoint document instead.

> The issuer URL and userinfo endpoint can be accessed by clicking on “URLs” on the left. Make note of the corresponding values for “issuer” and “userinfo_endpoint”.

https://zitadel.com/docs/guides/start/quickstart#referred1

The doc should also be updated to mention that the `userinfo_endpoint` needs to be fetched from the discovery endpoint document instead.

**Comment by hifabienne** [comment]
Hei @jbvv1 
Thanks for the report, we will have a look at it.
The url should actually still be shown, but also some screenshots are out of date.

**Comment by kbumsik** [comment]
@hifabienne 

Hi,

> The url should actually still be shown, but also some screenshots are out of date.

Not it doesn't show urls now. I know what OP is saying.

This is what the tutorial says, and the tutorial suggest using `userinfo_endpoint`:

![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/491332b3-81c9-4032-9181-c0a069098b17)



But, this is the current product:

![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/3477e2b8-d8c3-42dc-acc9-5a12e0823387)


This leads much confusions for newcomers because the suggested `userinfo_endpoint` is not shown to the user.

**Comment by hifabienne** [comment]
Sorry I maybe wrote a little unclear.
There is a bug in the frontend, thats why the url is not showing.
@peintnermax Is about to fix that. So the screenshots in that part should stay as they are, and we will have to fix the URL section in the console.

@dakshitha Will have a look at the onboarding guide, and change the screenshots where needed.

**Comment by peintnermax** [comment]
fixes the link section: https://github.com/zitadel/zitadel/pull/6469

**Comment by hifabienne** [comment]
I close this issue, as it has been fixed and also other screenshots are updated
