### ISSUE TITLE
German translations, "ZITADEL" in end user messages

### ISSUE THREAD

**Issue by some-user123** [zitadel/zitadel#6483]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the problem caused by this bug

- "Login" page description in English: "Enter you login data."
German (de): "Mit ZITADEL-Konto anmelden."
Better: "Bitte gib deine Anmeldedaten ein."

I would try to avoid using the term "ZITADEL" in all messages exposed to end users. End users are likely not aware of this brand name. So, this will lead either to confusion or al those messages need to be customized before ZITADEL can be used.

- "Initialize user" page description in German: "Bestätige deine E-Mail mit dem unten stehenden Code und legen dein Passwort fest."
Should be changed: "Bestätige deine E-Mail-Adresse mit dem unten stehenden Code und lege**~~n~~** dein Passwort fest."

- in German most button texts start with lower case, which is quite unusual. I think, this should be changed through the application, e.g. "Initialize user" page "weiter" to "Weiter", "Login" page "weiter" to "Weiter", "registrieren" to "Registrieren", ...

### To reproduce

See above

**Comment by hifabienne** [comment]
Hei @some-user123 
Thanks for the issue. You are right, it does make sense to change this, as its probably easier to handle as most will not want to state ZITADEL.
I would not see this as bug, and will remove the label and change to improvement.
We will have a look when we can get this in, otherwise also PRs are highly welcome if you like to contribute to ZITADEL.
