### ISSUE TITLE
[Bug]: User gets stuck when typing in address for their external account

### ISSUE THREAD

**Issue by thepaperpilot** [zitadel/zitadel#6574]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.36.3

### Describe the problem caused by this bug

If a user has registered via an external account, and they later try to login by typing in that email as their username, they'll get a screen that shows just their email, the error "External Login Provider not allowed" and a button to register or go to the next page. The "next" button just reloads that same UI, and the register button goes directly to registering with username + password. There's no way for the user to log in with the external account, other than manually changing the URL.

### To reproduce

1. Create an account via an external account
2. Log out
3. Go to login screen, and type in the email for the account
4. Now that you're on the "External Login Provider not allowed" error screen, you cannot get back to the login page

### Screenshots

<img width="317" alt="image" src="https://github.com/zitadel/zitadel/assets/3683148/7da5593e-38ba-4710-a03f-9cbee023f5e5">

### Expected behavior

The register button should go to the registration _options_ page, and the next button should go back to the login screen.

### Operating System

Device: Windows
Browser: Vivaldi

**Comment by thepaperpilot** [comment]
One more clarification: If you select the register button, there _is_ a login button at the bottom of that page, but for some reason that one then brings you back to logging in using username + password instead of letting you use the external account.
<img width="324" alt="image" src="https://github.com/zitadel/zitadel/assets/3683148/0d5f6688-ab41-410d-8d1c-72e42f0f2b48">
Specifically, because it brings you to `/ui/login/loginname?authRequestID=<redacted>`

**Comment by hifabienne** [comment]
Hei @thepaperpilot 
Not sure on your usecase and how you have configured your instance and organizations. but I try to explain some parts.
I think this depends on your configuration.
At the moment we do trigger the settings configured on the instance, when you open up the login.
When registering the user ends up on the default organizaiton, so if those settings do not match it can cause some problems.
If you want to trigger the settings of an organization directly, you have to send an organization scope urn:zitadel:iam:org:id:{id}https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes

The problem with the isntance and default organization we already have an issue here: https://github.com/zitadel/zitadel/issues/6567

**Comment by demircis** [comment]
Hi @hifabienne,

We have noticed that the same issue popped up for our customers where they get the "External Login Provider not allowed" when logging in. It used to work fine prior to the change to version v.2.35.x (I think).

In our case, the IDP is configured on the organization.

We have many customers which are represented as different orgs, but all customers log in using our (same) website. So there is no way for us to send the organization scope, since we do not know the org of the user who is about to log in.

**Comment by hifabienne** [comment]
For me it sounds like you have configure a provider on the instance level, that doesn't exist on the organisation where the user will be registered.
E.g when you have Google on your instance, but on the default organization not, then you will get that error.

@livio-a @stebenz Do you know if we have changed something in the later versions, that could cause that problem?

**Comment by thepaperpilot** [comment]
Oh, thank you @hifabienne! You are correct and the issue was simply a misconfiguration - I configured the IDPs in the instance settings and only approved them there. I just now went into my organization and enabled them there as well, and now when I type in the username and hit next, it redirects me to the IDP. I'm not sure if we should close this since it sounds like that wasn't the fix for demircis though.

**Comment by livio-a** [comment]
@hifabienne there was the change to "restrict AllowRegistration check to local registration" in https://github.com/zitadel/zitadel/releases/tag/v2.35.0, but that should not influence this.
I also use IDPs, which are only configured on the organization and not on the instance.

@demircis Can you please share your config:
- As far as i understood the IDP are all only configured and activated on the corresponding organization, right?
- What does the login policy (instance and org) look like, esp. the `Advanced` part: <img width="343" alt="image" src="https://github.com/zitadel/zitadel/assets/9405495/e4d7bddd-e474-46f8-bf7c-2c5ec785f7e7">
- And the additional options of one of your IDPs, where it does not work: <img width="464" alt="image" src="https://github.com/zitadel/zitadel/assets/9405495/9d42f6e8-76a8-4434-8abc-e810b54d08dc">

**Comment by demircis** [comment]
Hi @livio-a,

We have configured and activated the IDP on the organization, and we have an IDP configured on the instance as well, which is however only used for a handful of specific customers.

Here are the settings:
![Screenshot 2023-09-19 at 09 59 13](https://github.com/zitadel/zitadel/assets/22999224/fdea53ee-a6ef-4b2b-a379-ea978cfaf888)
![Screenshot 2023-09-19 at 09 59 56](https://github.com/zitadel/zitadel/assets/22999224/743302fe-aaff-4059-99fc-42bb8f4bf868)

Is it potentially related to the "map from the ID token" setting? because this is a new setting as far as I know and we did not explicitly set this to true. Would be nice if you could explain what this setting does since it is not documented.

Thanks

**Comment by demircis** [comment]
Hi @livio-a @hifabienne

Any updates on this? We have more and more customers complaining about this issue when they are trying to login and get this error message "External Login Provider not allowed"

**Comment by hifabienne** [comment]
> Hi @livio-a @hifabienne
> 
> Any updates on this? We have more and more customers complaining about this issue when they are trying to login and get this error message "External Login Provider not allowed"

Hei @demircis 
Can you please write what you have setuped and what you try to achieve?
So what you have on the instance, what organizations you have with what kind of configuration, with wich scopes you start the auth request, and which user tries to register?
Are you on self hosting or cloud?

**Comment by demircis** [comment]
Hi @hifabienne 

We are using Zitadel cloud.

On the instance, we have 1 IDP configured (google) as a generic OIDC IDP. These are the login settings set on the instance:
![image](https://github.com/zitadel/zitadel/assets/22999224/401c5df4-a3c8-40d4-866f-01186d28ed01)

For our customers, we configure a separate Azure IDP per customer org (currently using the generic OIDC type, but issue happened also with a Microsoft Provider IDP template). The configuration on the org for these customers is always the same (see screenshots in previous comment). We use domain discovery on the organizations to "send" the user to the correct organization which should then have the configured IDP. We also set the "add domain suffix to loginname" setting to true for these orgs.

In general, this error message also appears for users who already have an account on Zitadel linked to the IDP, so not only for registering.

We send the following scopes:
`openid profile email offline_access urn:zitadel:iam:user:metadata urn:zitadel:iam:org:projects:roles urn:zitadel:iam:org:project:id:{project_id}:aud`

let me know if you need any additional info.

Thanks

**Comment by hifabienne** [comment]
@demircis 
I setuped a test instance for myself and try to reproduce it, but it works fine for me.

Can you answer those questions:
Do you have multiple organisations? 
Which one is the default organisation?
On which organisation do you try to login?
Can you send a screenshot of the settings of your organization where you try to login?
What domains do you have registered on that organization?
How do you try to login? Username, etc.?

Or can you make a video of you trying to login, so we can see what happens? If you do not want to send those things in here because of personal data, you can send it to support@zitadel.com (please add a note that we discuessed that)

**Comment by demircis** [comment]
Hi @hifabienne,

I sent an email with all the information requested and a video.
