### ISSUE TITLE
[Bug]: PKCE response mode `fragment` not usable

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#6586]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

main

### Describe the problem caused by this bug

ZITADEL does not return the `response_mode` to the OIDC lib. This causes the issue that the response mode always falls back to query. 

### To reproduce

Try to request `response_mode=fragment`. You will get `response_mode=query` in the response.

### Additional Context

Reported by: https://discord.com/channels/927474939156643850/1151508313717084220

**Comment by kbumsik** [comment]
Hi, OP in discord here.
Thanks for double checking the issue!

I originally posted it believing it is not only a bug, but ZIDTADEL completely forget about `response_mode`.
It's because ZITADEL's doc and API references did not mention `response_mode`:

- https://zitadel.com/docs/guides/integrate/login-users
- https://zitadel.com/docs/apis/openidoauth/endpoints#required-request-parameters

If it supposed to support `response_mode` then it worth adding it in docs as well 👍 
It would be great if the doc clearly mentions full list of response_mode it supports, [like what Auth0 did](https://auth0.com/docs/authenticate/protocols/oauth#authorization-endpoint) (but of course we don't need non-standard `web_message` by Auth0).

**Comment by muhlemmer** [comment]
> - https://zitadel.com/docs/guides/integrate/login-users
> - https://zitadel.com/docs/apis/openidoauth/endpoints#required-request-parameters

In the [linked PR](https://github.com/zitadel/zitadel/pull/8145) I choose only to add `reponse_mode` to the endpoint reference. Because zitadel already used the appropriate response mode based on the application's response type. It is rarely a good idea to set this parameter, because:

1. Fragments are never send by a browser to the server. This means that setting `response_mode=fragment` on web apps will break most server-side apps. With the above fix zitadel will gladly build an URL with fragment and redirect the browser to that URL. But unless the target URL has a client-side JavaScript to parse and forward the fragment to the server, the server will never receive any parameters from the URL.
2. Fragment is already the default for implicit flow.
3. Query is already the default for Code flows.
4. As per [OpenID Connect Core 1.0, Section 3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest):

> This use of this parameter is NOT RECOMMENDED when the Response Mode that would be requested is the default mode specified for the Response Type.

The only exception is `reponse_mode=form_post` which is an additional standard: [OAuth 2.0 Form Post Response Mode](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html), but only works for server-side apps AFAIK,
