### ISSUE TITLE
[Bug]: Email code doesn't working when creating human user

### ISSUE THREAD

**Issue by pedrobruneli** [zitadel/zitadel#6600]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

As i mention on Discord

I'm trying to call the new create human v2beta api but when i try to use the returned code it's throwing code not found on Zitadel auth. 

### To reproduce

1. Call the endpoint POST /v2beta/users/human and send in the body "returnCode": {}, in email field
2. Example endpoint body: 
```
{
  "userName": "email@hotmail.com",
  "profile": {
    "givenName": "teste",
    "familyName": "teste",
    "nickName": "teste",
    "displayName": "teste"
  },
  "email": {
    "email": "email@hotmail.com",
    "returnCode": {},
    "isEmailVerified": false
  }
}
```

### Screenshots

1- Use code try 
![image](https://github.com/zitadel/zitadel/assets/96212888/c5e2b389-bf82-4eb1-94ce-5eb66637f6c8)

**Comment by hifabienne** [comment]
Hei @pedrobruneli 
I just tested this myself, and could reproduce.
First I tested, with adding the user with an initial password, and that worked perfectly fine because then the code is just to verify the email.
Then I tested without a password, and then I get the screen you show above. In that case ZITADEL Login UI, does expect an initialization code, but as it is an email verification code this doesn't work.

I actually think that this works as expected, as we want to get rid of the initialization code, but its not backwards compatible with our current hosted login. We will also change to a new login ui, that uses our new APIs, but we are not yet there.

@livio-a @muhlemmer Can you confirm that? Or did I miss-understand something?

**Comment by livio-a** [comment]
@hifabienne as discussed yesterday, we can update the current login to be able to handle this case as well. This is probably bigger than a normal bugfix friday issue.

For others stumbling upon this problem, there's a workaround by setting an "init password", e.g.
```
 "password": {
    "password": "Password1!",
    "changeRequired": true
  }
```

**Comment by hifabienne** [comment]
hei @pedrobruneli 
For your information.
We want to get rid of the initial state and the initial code. At the moment the new apis are not backwards compatible with our current login there.
As we are planning to also create a new login, that uses our new APIs. You can find it here: https://github.com/zitadel/typescript
So, its actually not a bug, but at the moment a decision, that we will not be fully backwards compatible.
If we see a high need of that, we will consider, making the changes in the current login.
