### ISSUE TITLE
[Bug]: Login Interface Texts reset and are not saved without error

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6766]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.39.1

### Describe the problem caused by this bug

An issue was reported via support, that Login Interface Texts can't be updated. Given a user is on the default organization, when they change a login text, then a successful response/no error is returned. After a couple of seconds the texts in Console are reset. The changes are not applied to the login interface.

### To reproduce

1. Go to the default organization
2. Change a text on the login interface texts (eg, Login > Next button)
3. Save
4. Wait a bit
5. Texts should disappear
6. Logout
7. Try to login, make sure to trigger the default organization
8. Login text should not be changed

### Screenshots

https://github.com/zitadel/zitadel/assets/1366906/91cb81f2-2585-49db-8d0a-12ee5ca8e17a

### Expected behavior

- Login texts should be persisted
- New login texts should be applied to the login form

### Additional Context

- Coverage of UI / e2e tests should be reviewed while fixing the underlying issue
- Maybe related to https://github.com/zitadel/zitadel/issues/6764

**Comment by muhlemmer** [comment]
At the moment I'm unable to reproduce both locally and on cloud. As the original issue #6764 mentioned, are there any failed events for you instance?

@adlerhurst will also have a look later today is there are spooler settings which might be set too tight.

**Comment by muhlemmer** [comment]
- I am able to reproduce on cloud when I'm changing a custom text twice.
- Locally with v2.39.1 and postgresql can't reproduce.

**Comment by brandan-schmitz** [comment]
I am having this issue with some of the of the login interface texts. I originally opened #6764 however I no longer see any failed events when trying to save some login texts and I can now save some of them after updating to v2.39.1 so I do not feel that issue is relevant. It is also not happening on all of them. For example, I can successfully save the one for `Login` but it will not save the one for `Register` or `Password`. It states that it has successfully saved it but as soon as you refresh the page or navigate away and then back to it they are back to the defaults again.

I am running v2.39.1 via kubernetes and installed through helm so it is using the official docker images. The database is cockroachDB v23.1.11 which is also in kubernetes and was installed via the official helm chart and is running in the secured mode with valid certificates for authentication.

**Comment by adlerhurst** [comment]
# Problem

Each change to the login texts creates about 300 events. If the project is not allowed to query so many events the projections get stuck.

# Workaround

Add the following lines to the config:

```yaml
Projections:
  Customizations:
    Projects:
      BulkLimit: 50
      TransactionDuration: 2s
    message_texts:
      TransactionDuration: 2s
      BulkLimit: 400
    custom_texts:
      TransactionDuration: 2s
      BulkLimit: 400
```

# Fix

Make sure that only changed texts are stored on command side
