### ISSUE TITLE
Extend Resoure API: User Grants

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7018]
We want to implement the user grants requests in our new resource based api.
We currently have multiple different names for the user grants depending on the place where we use it. So we also want to align that.

Proposal: User Roles

**Acceptance Criteria**
- [ ] Align naming to newly defined name (user roles?)
- [ ] Naming is aligned in documentation, new api, etc. In places where we cant use the new naming we have a note, that it in future xy is used.
- [ ] Create new service for user roles (is this needed? Or is it the user service?)
- [ ] Implement the following requests
      - [ ] User Role By ID
      - [ ] Search User Roles (query possibilities analog to current implementation (mgmt api))
      - [ ] CRUD 

**Additional Information**
Current Query in Management API:
- UserGrantProjectIDQuery project_id_query 
- UserGrantUserIDQuery user_id_query
- UserGrantWithGrantedQuery with_granted_query
- UserGrantRoleKeyQuery role_key_query
- UserGrantProjectGrantIDQuery project_grant_id_query
- UserGrantUserNameQuery user_name_query 
- UserGrantFirstNameQuery first_name_query
- UserGrantLastNameQuery last_name_query
- UserGrantEmailQuery email_query 
- UserGrantOrgNameQuery org_name_query 
- UserGrantOrgDomainQuery org_domain_query 
- UserGrantProjectNameQuery project_name_query 
- UserGrantDisplayNameQuery display_name_query 
- UserGrantUserTypeQuery user_type_query

**Comment by hifabienne** [comment]
@livio-a @muhlemmer can you please have a look at the issue for estimation?
Also if the proposed naming makes sense?

**Comment by muhlemmer** [comment]
> user roles?

We roles defined in project and those are granted to users. If grant is too technical, what about "user authorization" like we currently use in the console.

![image](https://github.com/zitadel/zitadel/assets/5411563/78fc9ae7-270c-49e4-89f2-99d1e95b7948)

> Create new service for user roles (is this needed? Or is it the user service?)

Yes. because it involves organization, projects and users.

>  Implement the following requests
> - [ ] User Role By ID
> - [ ] Search User Roles (query possibilities analog to current implementation (mgmt api))
> - [ ] CRUD
> - [ ] Bulk Remove

We believe that Get by ID and CRUD is enough for one sprint. Bulk remove as a concept is something we have to find a solution for in general. (We can't just create N amount of remove events, that gave issues already the custom texts for example.)

**Comment by eliobischof** [comment]
First, we do #7592, #7649 and #7650
