### ISSUE TITLE
[Bug]: Duplicate Key `events2_pkey` on Token Endpoint

### ISSUE THREAD

**Issue by maennchen** [zitadel/zitadel#7202]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

Cloud

### Database

None

### Describe the problem caused by this bug

When requesting tokens on the token endpoint, we get the following errors regularly:

`ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)`

### To reproduce

We use Zitadel in the conformance tests of [oidcc](https://github.com/erlef/oidcc).

Test: https://github.com/erlef/oidcc/blob/d57635e8a7bea3352ab2b4091fc1ec679663f884/test/oidcc_test.exs#L148

Example CI Run with failure: https://github.com/erlef/oidcc/actions/runs/7476817164/job/20348100452

### Expected behavior

Test passes every time

### Operating System

GitHub Actions on Ubuntu Latest

**Comment by hifabienne** [comment]
@livio-a @muhlemmer can you help here?

**Comment by alexandresoro** [comment]
I see similar logs on introspection endpoint too. 
Zitadel version `2.41.1` deployed via the official Helm chart. Database is PostgreSQL.

Basically, in my use case, I have a server that sends several requests to the introspection endpoint pretty much at the same time.

I see the following logs:

```
2024-02-13 13:29:55.544	
2024/02/13 12:29:55 WARN request error oidc_error.parent="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)" oidc_error.type=unauthorized_client
	
	
2024-02-13 13:29:55.529	
2024/02/13 12:29:55 WARN request error oidc_error.parent="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)" oidc_error.type=unauthorized_client
	
	
2024-02-13 13:29:55.505	
2024/02/13 12:29:55 WARN request error oidc_error.parent="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)" oidc_error.type=unauthorized_client
	
	
2024-02-13 13:29:55.504	
2024/02/13 12:29:55 WARN request error oidc_error.parent="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)" oidc_error.type=unauthorized_client
```

I don't see such errors when sending only a single introspection query, but it might be pure coincidence.

**Comment by muhlemmer** [comment]
@roquie the loglines you posted are 4 hours apart and probably do not have much to do with each other.

For the first logline: We've recently improved the error reporting in with OIDC which might result in error logs not present in earlier versions of zitadel. The error points this code:

https://github.com/zitadel/zitadel/blob/585988bd83824663895c965966f7e72ca701dd5b/internal/api/oidc/error.go#L32-L36

It means there is an error passed that was not wrapped in a way the OIDC layer can understand. That is one bug that needs to be fixed but probably has nothing to do with the bug from the OP or the later error

The second error `"could not push event \"user.machine.secret.check.succeeded\"` can only be printed during a client credentials grant on the token endpoint. As part of the optimizations in https://github.com/zitadel/zitadel/pull/6999 we removed other push cases. Furthermore the push is now async. If an error occurs it is logged but ignored. The request will still succeed.

@alexandresoro since `v2.42.0` the `user.machine.secret.check.succeeded` is no longer pushed during the introspection call as part of the performance optimizations from PR https://github.com/zitadel/zitadel/pull/6909, so that's probably why the OP only mentions the the token endpoint.

@maennchen as your issue is dated 11th of january and you are using Cloud, that must have been the v2.42 release. As you omitted the grant type you are using on the token endpoint it is hard to establish what is failing. But if the grant type is `client_credentials` and the origin of your error is the same as the other posts, the call should now succeed as we do not fail the request when we can't push the event. 

Of course, we will still need to investigate and fix the pushing of the event.

**Comment by maennchen** [comment]
@muhlemmer The test is using `urn:ietf:params:oauth:grant-type:jwt-bearer`: https://github.com/erlef/oidcc/blob/main/src/oidcc_token.erl#L609

**Comment by muhlemmer** [comment]
@maennchen thanks for the prompt answer. I believe I know enough to further debug the issue.

**Comment by maennchen** [comment]
@muhlemmer One thing that comes to mind is that there are parallel tests running. Therefore the requests cold be made in a very short timeframe.

**Comment by muhlemmer** [comment]
Small program to reproduce. Only able to trigger the same error with a high amount of `MaxOpenConnections` on the database. (Currently I set it to 1000)

```go
package main

import (
	"context"
	"log/slog"
	"os"
	"time"

	"github.com/zitadel/oidc/v3/pkg/client/profile"
	"golang.org/x/oauth2"
)

func main() {
	os.Exit(run())
}

const ParallelRequestN = 100

func run() (exit int) {
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()

	source, err := profile.NewJWTProfileTokenSourceFromKeyFile(ctx, "http://localhost:9000", "key.json", []string{"openid", "email"})
	if err != nil {
		slog.ErrorContext(ctx, "new JWT profile token source", "err", err)
		return 1
	}
	results := make(chan tokenResult, ParallelRequestN)
	for i := 0; i < ParallelRequestN; i++ {
		go func() {
			results <- newTokenResult(source.TokenCtx(ctx))
		}()
	}

	for i := 0; i < ParallelRequestN; i++ {
		result := <-results
		if result.err != nil {
			slog.ErrorContext(ctx, "result error", "err", result.err)
			exit++
			continue
		}
		slog.InfoContext(ctx, "result token", "token", result.token)
	}
	return exit
}

type tokenResult struct {
	token *oauth2.Token
	err   error
}

func newTokenResult(token *oauth2.Token, err error) tokenResult {
	return tokenResult{token, err}
}
```
