### ISSUE TITLE
Post Edit Profile Trigger

### ISSUE THREAD

**Issue by thepaperpilot** [zitadel/zitadel#7277]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I'd like to make API calls after a user updates their profile, to update their profile on other services as well. This could be done using the Actions system, except none of the triggers run following the user updating their profile.

### Describe your ideal solution

A trigger gets added so an action can be run after a user edits their profile

### Environment

Self-hosted

**Comment by mffap** [comment]
I think this might be similar to #7025

**Comment by hifabienne** [comment]
Yes I actually think it is the same.
I will close this issue here, to avoid duplicated.
@thepaperpilot feel free to reopen, if you think your usecase is different to the mentioned issue. Also would be great if you can upvote the other issue, so we can see some reactions, this helps us with the prioritization
