### ISSUE TITLE
[Bug]: audience of granted project not in `aud` claim

### ISSUE THREAD

**Issue by johakoch** [zitadel/zitadel#7345]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

I have two organizations: "org1" and "org2", with one project each: "org1p" and "org2p".
In "org1p" I have an API "org1p_api".
In "org2p" I have a web-type OIDC client "org2p_web" (Auth Token Type: JWT).

Project "org1p" has a grant to "org2", so that "org1p" is listed in org2's "Granted Projects".

In org2 I have a user.

Now, if this user logs in using the OIDC client "org2p_web" with scope "profile email offline_access urn:zitadel:iam:org:project:id:252855702316398078:aud" (252855702316398078 being the resource Id of the granted project "org1p"), I see in the instance's Events log the following "Access Token created" entry:
```json
{
  "applicationId": "252856053933356542@org2p",
  "audience": [
    "252856053933356542@org2p",
    "252855756087375358",
    "252855702316398078"
  ],
  "expiration": "2024-02-06T22:00:23.686200332Z",
  "preferredLanguage": "und",
  "scopes": [
    "openid",
    "profile",
    "email",
    "offline_access",
    "urn:zitadel:iam:org:project:id:252855702316398078:aud"
  ],
  "tokenId": "252862212748621310",
  "userAgentId": "252724384060413498"
}
```
Note the entry "252855702316398078" in the `audience` array. However the created access token does not show this ID in the `aud` claim:
```json
{
  "iss": "https://....zitadel.cloud",
  "sub": "252857104220565890",
  "aud": [
    "252856053933356542@org2p",
    "252855756087375358"
  ],
  "exp": 1707256823,
  "iat": 1707213623,
  "nbf": 1707213623,
  "jti": "252862212748621310"
}
```

See https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes:
> `urn:zitadel:iam:org:project:id:{projectid}:aud`	`urn:zitadel:iam:org:project:id:69234237810729019:aud`	By adding this scope, the requested projectid will be added to the audience of the access token

Is there any configuration that I miss to make this work?

### To reproduce

See description

### Expected behavior

I'd expect the granted project's resource Id to appear in the access token's `aud` claim.

**Comment by hifabienne** [comment]
hi @johakoch 
Thanks for reporting that bug.
Your use-case should actually work like you describe.
It looks like we do have a bug in the jwt token.
We do have a customer that has the same use case as you do have, but instead of using jwt tokens, they use opaque tokens with calling the userinfo endpoint.

So as a workaround you could also use the userinfo endpoint

**Comment by johakoch** [comment]
Hi @hifabienne
> So as a workaround you could also use the userinfo endpoint

The OIDC client implementation I use actually calls the userinfo endpoint with the access token. But why should the _user_ info endpoint give information about which audiences an access token could be used with? Or do you mean that the userinfo response should contain _roles_ from the granted project?

**Comment by buehler** [comment]
Hey @johakoch 

I have an open-source repository which relies on granting a project to other organizations. It seems that the generated JWT does not contain the audience.

I think what @hifabienne meant: as a workaround you can change to "Bearer Tokens" instead of JWT tokens. The target API must make an introspection call to check if the token is valid. And in there, the audience is correctly set.

You don't get the audience on the user info endpoint, but on the introspection endpoint if you check the provided token.

The API I mentioned is: https://github.com/smartive/cas-fee-adv-mumble-api
And the application: https://github.com/smartive/cas-fee-adv-mumble-auth-demo

Regards

**Comment by johakoch** [comment]
Hi @buehler , yes introspection makes more sense. I'll try that.

**Comment by johakoch** [comment]
Yep, in the token introspection response, the `aud` contains the requested ID. Thanks @hifabienne and @buehler

**Comment by schettn** [comment]
> Yep, in the token introspection response, the `aud` contains the requested ID. Thanks @hifabienne and @buehler

This works but I can't get the assigned roles of all audiences (Only the roles of the same projects as the OIDC application). Do you?

https://discord.com/channels/927474939156643850/1204446509291143179

**Comment by johakoch** [comment]
@schettn It seems that I do, yes.

**Comment by muhlemmer** [comment]
This should be fixed in: https://github.com/zitadel/zitadel/pull/7610 for release 2.49 and is back-ported to 2.48.2. I will close this, let me know it there are still any issues.
