### ISSUE TITLE
[Bug]: Password reset doesn't work

### ISSUE THREAD

**Issue by roquie** [zitadel/zitadel#7349]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.43.8

### Database

PostgreSQL

### Database Version

15

### Describe the problem caused by this bug

time="2024-02-07T08:27:25Z" level=warning msg="missing translation" args="map[ChangeDate:2023-11-30 11:54:34.880682 +0000 UTC Code:NJCVDJ CreationDate:2023-10-28 16:08:10.124462 +0000 UTC DisplayName: Test Pro FirstName:Test LastEmail:example@example.com LastName:Pro LastPhone: LoginNames:[@username] NickName: PreferredLoginName:@username UserName:@username VerifiedEmail:example@example.com VerifiedPhone:]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/i18n.go:210" error="message \"PasswordReset.Footer\" not found in language \"en\"" id=PasswordReset.Footer

### To reproduce

1. Click Logout
2. Click Login with password
3. Click Reset password
4. Open service logs

### Expected behavior

A message in my inbox.

**Comment by hifabienne** [comment]
Hei @roquie 
The message you see in the logs is only a warning and doesn't cause the problem.
I quickly checked the resent password myself, and it works perfectly fine.

Do you generally get any emails? Could there be a problem with your smtp settings?

**Comment by salvisbh** [comment]
The error can still be observed in the cloud instance if it is the same one. An email change of the admin at zitadel.com level, i.e. not within an instance, can be carried out in the user profile. The navigation triggered by the verification email confirms the successful mutation. Back in the initial tab, the changed email is displayed as Verified. After logging out and logging in again (user/password/second factor), the user profile contains the old eMail address again.
Context: I had to delete the instance due to another error. I had previously linked a Google account to the first user of the instance. It seems that this link has been passed on to the main admin. Why do I suspect this? In an incognito window, I always log in to zitadel.com with eMail. Nevertheless, for whatever reason, Zitadel thinks it has to redirect me to Google SSO, which I explicitly do not want here. Presumably some cookie has a hand in this: This forwarding request interpreted by Zitadel only happens in an incognito window and not in the browser I usually work with as a Zitadel admin. Unfortunately, the admin user profile does not contain an option to delete a background link between Google and the admin account.

**Comment by hifabienne** [comment]
> The error can still be observed in the cloud instance if it is the same one. An email change of the admin at zitadel.com level, i.e. not within an instance, can be carried out in the user profile. The navigation triggered by the verification email confirms the successful mutation. Back in the initial tab, the changed email is displayed as Verified. After logging out and logging in again (user/password/second factor), the user profile contains the old eMail address again. Context: I had to delete the instance due to another error. I had previously linked a Google account to the first user of the instance. It seems that this link has been passed on to the main admin. Why do I suspect this? In an incognito window, I always log in to zitadel.com with eMail. Nevertheless, for whatever reason, Zitadel thinks it has to redirect me to Google SSO, which I explicitly do not want here. Presumably some cookie has a hand in this: This forwarding request interpreted by Zitadel only happens in an incognito window and not in the browser I usually work with as a Zitadel admin. Unfortunately, the admin user profile does not contain an option to delete a background link between Google and the admin account. @hifabienne , you can verify the case in the Resource Id `256504025426465044`

Hi @salvisbh 
I am not sure if I understand your problem. Could you maybe open up a new bug report. And also add some screen recordings, so we can have a look what happens?

**Comment by salvisbh** [comment]
> > The error can still be observed in the cloud instance if it is the same one. An email change of the admin at zitadel.com level, i.e. not within an instance, can be carried out in the user profile. The navigation triggered by the verification email confirms the successful mutation. Back in the initial tab, the changed email is displayed as Verified. After logging out and logging in again (user/password/second factor), the user profile contains the old eMail address again. Context: I had to delete the instance due to another error. I had previously linked a Google account to the first user of the instance. It seems that this link has been passed on to the main admin. Why do I suspect this? In an incognito window, I always log in to zitadel.com with eMail. Nevertheless, for whatever reason, Zitadel thinks it has to redirect me to Google SSO, which I explicitly do not want here. Presumably some cookie has a hand in this: This forwarding request interpreted by Zitadel only happens in an incognito window and not in the browser I usually work with as a Zitadel admin. Unfortunately, the admin user profile does not contain an option to delete a background link between Google and the admin account. @hifabienne , you can verify the case in the Resource Id `256504025426465044`
> 
> Hi @salvisbh I am not sure if I understand your problem. Could you maybe open up a new bug report. And also add some screen recordings, so we can have a look what happens?

Hi @hifabienne , i will try to create a reproducer with a self-hosted instance after my holidays.
