### ISSUE TITLE
Include org_id in all activity logs

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7412]
To be able to make reports from our activity logs for instances and organizations we do need the organization id in each activity log.
At the moment requests in the "current" login do have the id, but the ones in the "new" login do not have an organization id.

## Acceptance Criteria
- [x] All activity logs include the organization id

**Comment by livio-a** [comment]
i just checked... the one event we originally found with the missing orgID is not the only one and some are even v1 oidc events, which will probably make it hard to pass the information through the whole process
since we anyway do not want the resourceOwner of the user to be part of these events, since they're not relevant for those, but only the activity logging, my proposal would be that the trigger function takes care of ensuring the orgID is set in the output

implementation detail: trigger is currently only a function and does not have access to the eventstore
