### ISSUE TITLE
[Bug]: Renaming an organization changes the domain

### ISSUE THREAD

**Issue by sebastianbuechler** [zitadel/zitadel#7550]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

This organization is newly created:
![image](https://github.com/zitadel/zitadel/assets/42775578/d0f2b94e-052f-4b32-b88d-a472ba3cdff5)

And it will have this verified domain (even though I did not verify it):
![image](https://github.com/zitadel/zitadel/assets/42775578/cc45f901-c04a-40e2-baf2-8c0a667bd188)

When I now want to rename it to "Test2" the primary domain changes:
![image](https://github.com/zitadel/zitadel/assets/42775578/2c9bb7e5-0dff-416a-86a4-ae9b525bf3d0)

And also the new domain is automatically verified: 
![image](https://github.com/zitadel/zitadel/assets/42775578/7e4789c8-89d7-4fe7-90ab-1a855b4cc6b6)

Should the primary domain change at all? Why is it automatically verified?

### To reproduce

1. Create new organization
2. Change name of organization
3. Check new domain

### Expected behavior

The domain should not be affected by a simple organization rename.

**Comment by hifabienne** [comment]
HEi @sebastianbuechler 
The first domain we add to the organization is computed by ZITADEL and is always added as verified, as it will not be possible to manually verify it. 
As the domain is computed by the organization name we also change it when the organization name changes.

We recommend adding a more specific domain that you specify instead of using the computed domain.

**Comment by sebastianbuechler** [comment]
Hi @hifabienne 
I'm not talking about the Zitadel domains, as we did not get a random domain in the first place but one from our own domain.
I think it's quite dangerous to change a domain without explicitly mentioning it during renaming as it can break the entire organization by changing all logins. Why change the domain at all on an internal renaming?

**Comment by hifabienne** [comment]
The organization domains also have a generated domain, here an example:
<img width="1405" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/5874cab1-1d77-4d8b-a12d-495583cc7e45">

The first domain is generated and is changed on the org name change.
The second one, which I added manually (customerd.com) is not changed when the organization name is changed

**Comment by sebastianbuechler** [comment]
@hifabienne I think that's the point: The first domain is not always generated as you can see in my second screenshot of the ticket. I created a new organization and I deleted no domain, but there was no *.zitadel.cloud domain present, only one of our domain. 

Thus a rename of the organization changed the custom domain, and also shows it as verified, even though it's not registered in the DNS.

**Comment by hifabienne** [comment]
Hei @sebastianbuechler 
The first domain is always generated, generated means organization name + Domain of your instance (URL where your ZITADEL runs)
Example: 
ZITADEL Instance Domain, where ZITADEL runs: login.acme.com
Organization: Test - generated domain test.login.acme.com

If you now rename the organization to test2 the domain will be changed to test2.login.acme.com

If you do want to avoid that we recommend adding another domain such as test.com, or test2.com so it will not be automatically changed.

The reason why we automatically change the domain as well is that we do have 2 unique identifiers for organizations, the name and the id. As the name of the name is unique we generate the domain out of it. So this means if we change the name we also need to change the domain, as otherwise it could happen that you get the same domains for a second organization with a previously used name.

Do your users authenticate with the generated domain? e.g user1@test.login.acme.com?
Or where do you run into problems when the domain changes?

**Comment by sebastianbuechler** [comment]
@hifabienne Thanks for the explanation. I think we will just create the domain manually in this case. 

The problem is that the domain is fixed in the application with the use of the primary domain (in the scopes) so that the users do not have to specify the domain during login. Since this is fixed it breaks the application.
