### ISSUE TITLE
Locally generate private key for service user

### ISSUE THREAD

**Issue by aDogCalledSpot** [zitadel/zitadel#7554]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Private keys generally should not be sent over the network. I would like to be able to create a service user with a private key that has been generated locally.

### Describe your ideal solution

Add an optional parameter to the request body of the [add machine key](https://zitadel.com/docs/apis/resources/mgmt/management-service-add-machine-key) which accepts an RSA public key. The JSON returned by the endpoint has the same fields as before but is missing the `key` field.

```json
{
    "type":"serviceaccount",
    "keyId":"100509901696068329",
    "userId": "100507859606888466"
}
```

### Version

v2.46.0

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog to collect feedback.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by aDogCalledSpot** [comment]
> Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

If you can give me pointers on where I need to look then I could see if I have the time to do this (e.g. what files would be affected, where does documentation need to go, etc).

**Comment by aDogCalledSpot** [comment]
I would still be interested in implementing this. I unfortunately don't have the time to read myself into a large codebase. If you could give me a high-level overview of what I should be looking into it would already save me a lot of time and I could open a PR soon-ish.

**Comment by livio-a** [comment]
Hey @aDogCalledSpot 

I'll try to cover the most important parts:
1. you'll have to extend the management servie (i'd add an additional endpoint, similar to the existing creation):
https://github.com/zitadel/zitadel/blob/main/proto/zitadel/management.proto#L1725-L1755
2. which is then implemented here: https://github.com/zitadel/zitadel/blob/main/internal/api/grpc/management/user.go#L775-L790
3. easiest is to probably follow the implementation from there
4. since we rely on [CQRS and eventsourcing](https://zitadel.com/docs/concepts/architecture/software), the created event is then handled in the projection: https://github.com/zitadel/zitadel/blob/main/internal/query/projection/authn_key.go
5. the query / read part (also used by the management service implementation (2)) is in here: https://github.com/zitadel/zitadel/blob/main/internal/query/authn_key.go

Let me know if this works for you or if you need additional information

**Comment by aDogCalledSpot** [comment]
Thank you so much! I'll have a look later today :)

> i'd add an additional endpoint, similar to the existing creation

My first approach would have been to extend the existing and add an optional parameter "pubkey" and to make the "key" field in the returned object optional as well (i.e. not present if "pubkey" was in the request).

What issues do you see with this approach?

**Comment by livio-a** [comment]
> Thank you so much! I'll have a look later today :)
> 
> > i'd add an additional endpoint, similar to the existing creation
> 
> My first approach would have been to extend the existing and add an optional parameter "pubkey" and to make the "key" field in the returned object optional as well (i.e. not present if "pubkey" was in the request).
> 
> What issues do you see with this approach?

Ah sure, that should work out as well.
