### ISSUE TITLE
[Bug]: mismatch data format (camelCase) between APIs/id_token

### ISSUE THREAD

**Issue by Yberion** [zitadel/zitadel#7790]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.50.1

### Database

PostgreSQL

### Describe the problem caused by this bug

Hello,

I'm not sure if this is a bug.

When requesting any api from https://zitadel.com/docs/apis/apis, the returned data (json) are formatted as `camelCase`.

![image](https://github.com/zitadel/zitadel/assets/4186385/0dffe066-ed1a-4bde-a7bd-360d4f5d5297)

This does not align with the returned data/json from the `userinfo` endpoint `/oidc/v1/userinfo` as well as in the `id_token` which are in `snake_case`.

![image](https://github.com/zitadel/zitadel/assets/4186385/f622de27-bc99-4f2e-9680-97256d11db7a)

I've also noticed that the schema itself does not match, for example:

- `locale` in the `userinfo` endpoint / `id_token`
- `preferredLanguage` in all other APIs
- Same goes for `username` (no idea what is `preferredLoginName`) vs `preferred_username`
- ...

I'm using the `userinfo` endpoint to create my user object in my Angular app.
Having different "cases" forces to have converters/boilerplate and add in complexity.
For example on Angular I can create query params from an object https://stackoverflow.com/a/65942191, having different case mean that we need a converted and 2 types.

This is probably a similar issue to the `gender` not having the proper format https://github.com/zitadel/zitadel/issues/7787

The real question is, should we rely on the `id_token`/`userinfo` to get information of the user?

I myself think that the answer is yes as it contain all other informations that we can get with the scopes, for example metadatas.

### To reproduce

- Call the userinfo endpoint `/oidc/v1/userinfo` (or decode the `id_token`)
  - it will return the gender as `male`, ...
- Call any API from https://zitadel.com/docs/apis/apis
  - it will return the gender as `GENDER_MALE`

### Expected behavior

Same case format on all endpoints + id_token.

**Comment by livio-a** [comment]
Hey @Yberion 

I can see the problem, but there's not much we can do about it, since different RFC / specification require different casing, formatting or even naming. And they might not represent the exact same thing.
For example the username all more or less the same meaning:
- OIDC defines a `preferred_username`
- OAuth (Introspection) defines the `username`
- SCIM uses`userName`
Since ZITADEL knows the concept of suffixed usernames, we currently call them loginnames.
Also similar to `gender` there are different formats for the "same" properties, e.g. dates in oidc are typically expressed as unix timestamps where our apis rely on date(time).

Regarding your question which to use:
There's no one rule fits all answer to that and depends on what you need.
If your application "only" requires authentication/authorization you could go with OIDC and use id_token / userinfo, resp. OAuth2 introspection on the API.
If you however also need to manage users in the same application / api, you will need to additionally use the proprietary endpoints and types.

**Comment by Yberion** [comment]
Hello @livio-a, thanks for the answer, I can understand the constraints, I will manage it on my side. 😄
