### ISSUE TITLE
[Bug]: Date Picker for PAT expiration date is unusable on Firefox

### ISSUE THREAD

**Issue by wlinna** [zitadel/zitadel#7877]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.49.2

### Database

PostgreSQL

### Describe the problem caused by this bug

Date Picker for PAT expiration date is unusable on Firefox. The layout is completely broken.

### To reproduce

1. Log in to Zitadel using Firefox as Zitadel Admin (or other user with sufficient privileges)
2. Create a Machine User
3. Open Machine User's settings
4. Open Personal Access Tokens
5. Click + Add. A small dialog opens
6. Click the calendar icon
7. Select year and month
8. Try to set day. Where are the numbers??

### Screenshots

![DatePickerBrokd](https://github.com/zitadel/zitadel/assets/1473454/52735671-05b7-4adf-ada9-a554c87a3c43)

### Expected behavior

A properly rendered Date Picker similar to what you'd see with Chromium.

### Operating System

Pop!_OS 22.04
Firefox 125

### Relevant Configuration

The problem occurs in both Light and Dark mode

**Comment by doncicuto** [comment]
Hi there, the issue is tricky. There's a problem on how Firefox is treating this style:

https://github.com/zitadel/zitadel/blob/fb8cd18f93e55e7ffa6612f1452b100fd7e8a01e/console/src/styles/table.scss#L74C1-L77C4

If I remove !important everything works fine for the calendar in Chrome and Firefox, but I've to study further the impact of this change in other Zitadel tables before sending a PR
