### ISSUE TITLE
[Bug]: TOTP app registration fails if the requested user is not the same as the authenticated one

### ISSUE THREAD

**Issue by ashep** [zitadel/zitadel#7944]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.49.1

### Database

PostgreSQL

### Describe the problem caused by this bug

When I try to [start the registration of a TOTP generator for a user](https://zitadel.com/docs/apis/resources/user_service/user-service-register-totp) using bearer token that is not belongs to the requested user, but to the IAM owner, I get the `Request user not equal to authenticated user (AUTH-Bohd2)` error.

### To reproduce

Create a new user:

```sh
curl --request POST \
  --url http://zitadel:8081/v2beta/users/human \
  --header 'Authorization: Bearer IAM_OWNER_TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
	"userId": "theUserID",
	"email": {
		"email": "theEmail@localhost",
		"isVerified": true
	},
	"profile": {
		"givenName": "theGivenName",
		"familyName": "theFamilyName"
	},
	"password": {
		"password": "theP@$$word1"
	}
}
'
```

Try to start the registration of a TOTP generator for a user:

```sh
curl --request POST \
  --url http://zitadel:8081/v2beta/users/theUserID/totp \
  --header 'Authorization: Bearer IAM_OWNER_TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{}'
```

Response:

```json
{
	"code": 7,
	"message": "Request user not equal to authenticated user (AUTH-Bohd2)",
	"details": [
		{
			"@type": "type.googleapis.com/zitadel.v1.ErrorDetail",
			"id": "AUTH-Bohd2",
			"message": "Request user not equal to authenticated user"
		}
	]
}
```

### Expected behavior

To be able to start the registration of a TOTP generator for a user on behalf of the IAM owner.

**Comment by ashep** [comment]
Hello @hifabienne! Is there any news about this? I probably misunderstand the concepts behind this API.

The question is: if I have to authenticate the request to this endpoint using the user's access token, why must the user ID be provided as well?

On the other hand, why isn't it allowed to perform the request on behalf of another user who has enough privileges, say, an IAM owner?

I really appreciate any help you can provide.

**Comment by hifabienne** [comment]
@stebenz @eliobischof can you help here?

**Comment by stebenz** [comment]
@ashep There is the option to provide a PasskeyRegistrationCode as an IAMOwner to add the Passkey to the user without being the respective user yourself.

You can create a [passkey registration link](https://zitadel.com/docs/apis/resources/user_service_v2/user-service-create-passkey-registration-link) with "returnCode", and then use this code for [registering the passkey](https://zitadel.com/docs/apis/resources/user_service_v2/user-service-register-passkey).

I'm not quite sure why this is a limitation, but I guess it was from before the full implementation of the v2 API.

@hifabienne I will move this into the backlog, the would be only one thing to change:
- [ ] add permission check to RegisterUserPasskey command, so that users with enough permission can also register a passkey for other users
