### ISSUE TITLE
[Bug]: session in version2 don't work correct

### ISSUE THREAD

**Issue by AmirhoseinBrz** [zitadel/zitadel#8212]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Database

CockroachDB

### Describe the problem caused by this bug

when i want use get session's with this api 
https://zitadel.com/docs/apis/resources/session_service/session-service-list-sessions
i can't get any session and i try every possible query search and result is 
`{"details":{"timestamp":"2024-06-30T06:31:53.276622Z"}}`
for every request i made
can anyone help me ?

### To reproduce

https://zitadel.com/docs/apis/resources/session_service/session-service-list-sessions

**Comment by doncicuto** [comment]
Hi @AmirhoseinBrz, first of all I'd recommend you to join the [Discord channel](https://zitadel.com/chat) as you may have a quicker way to ask and find answers to your questions.

I presume that you're building your own Login UI as the session API is intended to manage sessions in a ZITADEL instance in a scenario where you create your own Login UI.

If you're following the [Build your own Login UI](https://zitadel.com/docs/guides/integrate/login-ui) documentation and you've been able to initiate sessions, maybe the issue is that your service user (the one associated with your bearer token) may not have the right permissions? I'd start to add the service user the IAM Owner permission to discard that your requests are not discarded due to lack of permissions.

![image](https://github.com/zitadel/zitadel/assets/30386061/316989be-62ea-49bf-af6d-1a36d540378a)
