### ISSUE TITLE
[Bug]: `setMetadata` in Zitadel action sets different value than from console

### ISSUE THREAD

**Issue by lukasver** [zitadel/zitadel#8338]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.56.0

### Database

PostgreSQL

### Database Version

15

### Describe the problem caused by this bug

Setting metadata to an user using Zitadel Actions generates a different value than when metadata is set from the console. Value set from action is wrapped in double quotes (""), while the one set from the console is not, thus the base64 encoded value received from the `userInfo` endpoint differs.

**Action being used**
```
function add_metadata_machine(ctx, api){
const user = ctx.v1.getUser();

// If user is not machine user then return
if (user.machine == undefined) {
  return
}

api.v1.user.setMetadata('test-from-action', 'some-string');

}
```

### To reproduce

1) Create the Zitadel action and configure it to complement Token, pre userinfo creation.
2) Call userinfo endpoint with a service user PAT.
3) Go to console and check user metadata.
4) Manually add a value to compare.
5) See difference.

### Screenshots

![image](https://github.com/user-attachments/assets/3f88f24b-0210-4b39-9fe0-4361360169f6)
![image](https://github.com/user-attachments/assets/e9de02b8-e096-4521-aba8-3123ffdc97f4)

### Expected behavior

Consistency is expected on the format of the value set no matter from where it was set.

**Comment by livio-a** [comment]
Was no also noted by an onboarding customer.

Looks like actions use json to serialize the value. @adlerhurst can we maybe have a quick look into this together?

**Comment by livio-a** [comment]
after the discussion with @adlerhurst I did some more investigation:
- the internal format of the values is []byte -> JSON respresentation (userinfo endpoint and APIs) is base64 encoded string (as shown in the screenshot above)
- actions use the JSON serialization since the values passed could any type incl. objects, booleans, ...
  -> strings are therefore quoted  `"` (JSON string)
- Console UI handles base64 en/decoding of the value and therefore also allows string values without quotes

Currently I don't see any easy solution without breaking change. Actions can be changes easily and I don't want to add any decision magic about the quoting in Console. Also metadata claims serialization can't be changed without a breaking change.
The way forward IMO is to finalize user schema: https://github.com/zitadel/zitadel/issues/6433

As alternative to the metadata claim in the userinfo, there's the possibility of setting the required claims using an action.
This will also remove the requirement of decoding the value on the client side, since it will directly set it as JSON value.
Metadata:
```json
"urn:zitadel:iam:user:metadata": {
  "test1": "dGVzdA",
  "test2": "dHJ1ZQ"
}
```

using action below:
```json
"test1": "test",
"test2": true
```

```javascript
function metadata_claims(ctx, api) {
  const metadata = ctx.v1.user.getMetadata();
  metadata.metadata.forEach(({ key, value }) => {
    api.v1.claims.setClaim(key, value);
  });
}
```

**Comment by stebenz** [comment]
I will close this issue for now, as there is a solution available, otherwise use userschema in following releases.
If this doesn't solve your problem, please reopen this issue.
