### ISSUE TITLE
[Bug]: Can not remove project grant

### ISSUE THREAD

**Issue by quochuydev** [zitadel/zitadel#8685]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.60.x

### Database

PostgreSQL

### Describe the problem caused by this bug

I can grant a project successfully owned by org **Company**, with header `x-zitadel-orgid` org **Customer** and using token Role IAM.
https://zitadel.com/docs/apis/resources/mgmt/management-service-add-project-grant

When I remove that grant ID with the header `x-zitadel-orgid` org **Customer**. it returns the error: `Project not found`
And If I remove that grant ID with the header `x-zitadel-orgid` org **Company**. it returns the error: `Grant not found`
https://zitadel.com/docs/apis/resources/mgmt/management-service-remove-project-grant

**Expected**: header `x-zitadel-orgid` org **Company** should be successfully

**Comment by hifabienne** [comment]
Hi @quochuydev 
I think the problem is the first request where you set the project. 
The grant should be set from the perspective of the company, so the header org id should also be from Company and not from customer

Can you try it again, with the other header.

Process:
Company sets a grant for a project to customer (in context of company)
Now the company sees the project grant in the list
And customer sees it listed in the granted projects

Also removing the grant should happen in the context of the company then

**Comment by quochuydev** [comment]
That's correct, I did a hotfix, but it just corrects data from now. Should you count it as a bug and do a fix for the removing grant API?

**Comment by quochuydev** [comment]
yes, that right

**Comment by hifabienne** [comment]
Ok thanks, I actually think we will have to look into the data to figure out how it is stored, and fix the add request, so this can't happen again.
I added the issue to the investigation so the engineers can have a look at it.

**Comment by stebenz** [comment]
Normally the data should be as follows:
- Company Org
  - Project
  - Project Grant
- Customer Org
  - User
  - Authorization (Usergrant) for granted project 
  
What happened now:
- Company Org
  - Project
- Customer
  - Project Grant Org
  - User
  - Authorization (Usergrant) for granted project 
  
As the logic always tries to find an existing project and projectgrant in the same organization, with the current logic we can't solve this problem. 
So to my questions:
- why do we check if the project exists to remove a projectgrant?
- why do we check for the project state when updating the roles of the projectgrant?
- why do we check for the project state when deactivating a projectgrant?
- why do we check for the project state when reactivate a projectgrant?

If you remove the project, and there could be the situation that the projectgrant is not removable anymore. IMO the command side should not check if a project is existing but instead check that the project is not yet removed as the project grant belong to the project aggregate.
@hifabienne how should we prioritize this?

**Comment by hifabienne** [comment]
In my opinion we should do at least the following fix:
- Ensure project grants can't be created on the wrong organisation to avoid future corrupt data

@quochuydev 
Do the wrongly created project grants somehow pop up in your request? or are they just created but never show up?

I think we should at the moment rather focus on cleaning the data, because the other checks, are not really neccessary but should also not be a problem, if the data would have been created initial in the correct way.

I guess we can add the issue to the bug fixing column, as it should not be a big change and do it somewhere inbetween.

**Comment by quochuydev** [comment]
API gets granted, but projects will still be correct on the customer side. Until we do the license management feature, I can't remove that grant anymore. should you consider updating the removed API too? it is like an edge case for checking the resource owner.
