### ISSUE TITLE
[Bug]: User invite using v2 api does not set the user state to initial

### ISSUE THREAD

**Issue by demircis** [zitadel/zitadel#8832]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.62.8

### Database

None

### Describe the problem caused by this bug

When first creating a user using the v2 user service `AddHumanUser` endpoint (with email explicitly set to not verified, and without setting a password), and then creating an invite code for that user using `CreateInviteCode`, the state of the created user is `Active`.

### To reproduce

1. Create a human user using the v2 api (set email verification to not verified and provide no password)
2. Create an invite code using the v2 api
3. observe the state of the created user (prior to initializing the user using the link from the invite email).

### Expected behavior

I expect the status of the invited user to be `Initial` until the user has set their password.

I'm not entirely sure if this is intended behavior or not, so this might not be a bug. but we rely in our application on the user state to communicate to admins/other users if the user has accepted the invite or not. With the v2 api we cannot do this anymore.

### Additional Context

From quickly searching through the code, I saw that there is a difference in handling the init events from v1 to v2:
V1: https://github.com/zitadel/zitadel/blob/32bad3feb3e260444d385c009b3898eb98060448/internal/command/user_human_init_model.go#L55
V2: https://github.com/zitadel/zitadel/blob/32bad3feb3e260444d385c009b3898eb98060448/internal/command/user_v2_invite_model.go#L58

**Comment by hifabienne** [comment]
Hi @demircis 
Yes you are right that the state is active, thats on purpose.
With the new v2 api we got rid of the initial state.
In the v1 APIs we did an assumption of what initial means, but this might not be the case for each use case.
Thats why we don't support the inital state anymore.
The user will be created active, and you have additional attributes/states you might want to check. like is the email verified or not.
Due to this I will close the issue.
